### ISSUE TITLE
Always in foreground

### ISSUE THREAD

**Issue by Jawler** [supertriodo/Arena-Tracker#10]
Sometimes the tracker is always in foreground. I can hover buttons in Hearthstone, where the tracker overlaps but i  can not click them any more.

**Comment by supertriodo** [comment]
The tracker was designed to be always on top of everything. If you tell me whas would be your desired behaviour mabye I can help you customizing it.

Here you can check an example of how I use it:
https://www.youtube.com/watch?v=U-XzJZ5UG2k

**Comment by Jawler** [comment]
Okay this makes sense. When multitasking it can be annoying, but there is a minimze button. 
Do you plan to implement tracking the opponents's deck? I know that this does not mak muche sense for arena, but since this tracker is the only one working for Linux some people use it for casua/ranked. Also it would be nice to see which cards he kept during mulligan.

**Comment by supertriodo** [comment]
I will add tracking opponent deck to future features.

About tracking enemy hand, is already done in the hand tab, You chan check the turn every card of the opponent was drawn (turn 0 means kept from mulligan), card returned to hand or card generated by other cards, it's pretty useful.

**Comment by Jawler** [comment]
Okay thanks for the information.

**Comment by supertriodo** [comment]
Thanks for your donation!

**Comment by Jawler** [comment]
You're welcome. I am really glad to see someone working on a version that also runs on Linux. Since i dont have time to contribute code I thought I should at least donate something.
