### ISSUE TITLE
Mana curve not being considered

### ISSUE THREAD

**Issue by SnnowRoyale** [supertriodo/Arena-Tracker#102]
When drafting at the HearthArena.com it have a tierlist with static values for each card but IT ALSO always consider the current mana curve of the drafted deck. This software does not, it only consider the static value of the card. Can it be improved?

**Comment by SnnowRoyale** [comment]
When using the Overwolf's HearthArena plugin, the user log in at HearthArena and do the do the draft simultaneosly at the client + site.

**Comment by supertriodo** [comment]
Arena Tracker is not HearthArena. Draft is the most fun part of arena and I don't want to make a software that tell you just pick this card and skip the draft.

AT shows static tier lists of LF and HA, if you have premium there are a lot of more information to help you make your choice. Check the [user guide](https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/drafting-tab.html) to learn all it those.
