### ISSUE TITLE
Program breaks when selecting wrong HS location folder

### ISSUE THREAD

**Issue by Bralwen** [supertriodo/Arena-Tracker#103]
Hi!

I accidentally managed to select the wrong folder for my HS location the first i launched the Arena Tracker, and now it thinks I have 0 cards.

![image](https://user-images.githubusercontent.com/45099951/48625351-3dca0b00-e9af-11e8-9e62-f9e41bd5059e.png)

Thank you

**Comment by Bralwen** [comment]
Forgot to mention, I tried deleting the Arena tracker folder + .exe and reinstalling, did not fix the problem

**Comment by supertriodo** [comment]
Hi,
Try pressing ctr_r while AT is on focus, then restart it. This will force
it to reset your configuration and go again over the setup process.
Let me know how it goes.

**Comment by Bralwen** [comment]
That did it! Thanks :)
