### ISSUE TITLE
Win being Recorded as a Loss

### ISSUE THREAD

**Issue by PJP2810** [supertriodo/Arena-Tracker#104]
As the title suggests, a game I won was recorded as a loss.

First time using the app, so unsure if there's a way to manually adjust the game to be a win. The replace on track-o-bot is displaying the game as a win also. I'll provide the replay in case it could help you digure out what caused the incorrect recording on the app.

https://www.zerotoheroes.com/r/hearthstone/5c14538f95b7c411b013d843

**Comment by supertriodo** [comment]
Mmmm... that's strange, the game in your trackobot stats appear as a win, but in the game tab as a loss... really strange because they share the same info, I'll take a look at the code but let me know if it happens again.

**Comment by PJP2810** [comment]
That's what I found so strange. When I went to trackobot I was expecting it to be listed as a loss and the error to be on the trackobot's side.
