### ISSUE TITLE
Syncing decks from the Play screen

### ISSUE THREAD

**Issue by foresto** [supertriodo/Arena-Tracker#106]
Hearthstone Deck Tracker automatically syncs all my decks when I enter Hearthstone's Play screen. It's a lot more convenient than having to wait until all cards in a deck are played in a game, and would be a nice feature for Arena Tracker.

**Comment by supertriodo** [comment]
Hi,
HDT does some stuff AT doesn't because it reads what Hearthstone is doing in RAM through a library they have created and maintain. That library is not ready for Windows/Mac/Linux, what is mandatory for AT, as I won't let any main OS behind.

Thanks for your suggestion though ;)

**Comment by supertriodo** [comment]
Maybe you don't know it but you don't need to let AT autocomplete a deck by playing it, you can just copy its deckstring in HS and create a deck in AT with it.

Check the user guide:
https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/player-deck-window.html#importclipboard

**Comment by foresto** [comment]
> Maybe you don't know it but you don't need to let AT autocomplete a deck by playing it, you can just copy its deckstring in HS and create a deck in AT with it.

I did know that, but unfortunately, it's still a pain when I have more than a few decks, or when I modify decks regularly.

> HDT [..] reads what Hearthstone is doing in RAM through a library they have created and maintain.

Interesting. Any chance you know where the source code lives? Nothing obvious jumped out at me in a quick browse of their github repo.

> I won't let any main OS behind.

<3
