### ISSUE TITLE
6.8.1 Required Library Changes

### ISSUE THREAD

**Issue by specialseth** [supertriodo/Arena-Tracker#107]
Does version 6.8.1 now require GLIBC 2.27? Since updating I am unable to launch with a missing library error

./ArenaTracker: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found

To my knowledge nothing else with my system has changed.  Running Linux Mint on the 4.15.0-48 kernel.

What are the recommendations for working around this problem?

**Comment by supertriodo** [comment]
Hi, I knew some problems would arise as I changed my build environment.
Which version of Linux Mint are you using? 19.1?

**Comment by specialseth** [comment]
18.3

**Comment by supertriodo** [comment]
Ok, try to download and use the appImage from the download section, let me know if that works for you.

**Comment by supertriodo** [comment]
Let me know if the AppImage version works for you. If not I'll have to come back to my old building setup for people who still uses old ubuntu versions.

**Comment by specialseth** [comment]
./ArenaTracker.Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./ArenaTracker.Linux.AppImage)
./ArenaTracker.Linux.AppImage: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_ArenaTfErFIO/lib/libpng16.so.16)

So if I upgrade to Linux Mint 19.1 this problem would be resolved? I can be easily convinced to upgrade :)

**Comment by supertriodo** [comment]
Ok, thx for trying out.
Yes, if you upgrade to Linux Mint 19.1, the new AT will work. You can try it from the usb live session before comitting to format your hard drive.

**Comment by supertriodo** [comment]
Great. It's my fault for using a modern distro as build environment, but I was eager to remove an old library dependency (png12) caused by my older distro build environment.
