### ISSUE TITLE
trojan:script/foretype.A!ml

### ISSUE THREAD

**Issue by gouverneur80** [supertriodo/Arena-Tracker#108]
when i downloaded the Arena.tracker.V6.81.windows.zip
my virus scanner detected a trojan:script/foretype.A!ml. Is this normal or must this not be in there?

**Comment by supertriodo** [comment]
This is not the first time I've heard of antivirus complaining about the windows version of AT. Not much I can do, AT is an open source project with nothing malicious hidden inside it.

You can use it safely.

**Comment by gouverneur80** [comment]
oke but my windows defence virus scanner put it in quartine
