### ISSUE TITLE
log.config (Arena Tracker + trackobot)

### ISSUE THREAD

**Issue by supertriodo** [supertriodo/Arena-Tracker#11]
[LoadingScreen]
LogLevel=1
ConsolePrinting=true
FilePrinting=true

[Power]
LogLevel=1
ConsolePrinting=true
FilePrinting=true
Verbose=1

[Zone]
LogLevel=1
ConsolePrinting=true
FilePrinting=true

[Arena]
LogLevel=1
ConsolePrinting=true
FilePrinting=true

[Asset]
LogLevel=1
FilePrinting=true

[Bob]
LogLevel=1
FilePrinting=true

**Comment by soli** [comment]
Hi there,

so, I tried this out, unfortunately track-o-bot rewrites the file each time it starts up. Worse than that, it actually replaces the `ConsolePrinting=true` statements with `FilePrinting=true` statements (ending with duplicates). I'll open an Issue with @stevschmid and in the meantime will replace the log.config myself after starting both track-o-bot and ArenaTracker…

**Comment by supertriodo** [comment]
The new version, coming really soon, will change the logging method from consolePrinting to filePrinting, so I think the trackobot rewrite shouldn't be a problem anymore. 

I'll post in Arena Tracker reddit when is out.

**Comment by soli** [comment]
Great, thanks a lot (didn't get any answer on the trackobot side unfortunately…).
