### ISSUE TITLE
Nothing happens when launching AT

### ISSUE THREAD

**Issue by roboserg** [supertriodo/Arena-Tracker#111]
So I start HS (tried windowed as well), I run AT (ver. 7) as admin (tried non admin as well) and I don't see card scores in the arena selection screen - https://puu.sh/DI4tF/30a4d12b9c.jpg

Help?

**Comment by supertriodo** [comment]
Don't use AT as admin. Check the user guide, if you are already in the middle of a draft you need to use the button "Force Draft", check the user guide: https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/drafting-tab.html#draftingadvice

**Comment by roboserg** [comment]
Thanks!
