### ISSUE TITLE
Tracker discards mirror entity as a possible secret after mech is magnetised to another mech

### ISSUE THREAD

**Issue by diamondAlex** [supertriodo/Arena-Tracker#112]
Opponent played a secret, the possible secrets appeared as intended. I magnetised a mech on another mech and mirror entity was removed from the list of possible secrets. Magnetising mechs doesnt proc mirror entity therefore it shouldn't have been removed. Thx.

**Comment by supertriodo** [comment]
Fixed. Should be ready on next release very soon. Thanks for your help!
