### ISSUE TITLE
Interface doesn't scale to 4k

### ISSUE THREAD

**Issue by jvook** [supertriodo/Arena-Tracker#114]
The interface is too small to use on 4k resolution. Adjusting DPI settings manually seems to break OCR of the cards.

I work around it by switching desktop res to 1080p

**Comment by supertriodo** [comment]
Hi,

There are 3 different elements to consider when adjusting to high res screens:

- Buttons and sliders used to configure AT (mostly in config tab). This elements won't adjust their size so they will look tiny in a 4k screen. Nevertheless you don't need to look at them and use them constantly while playing HS so they don't are so big of a deal.

- Overlays shown during the draft. When you start a new draft the scores shown below the cards and the mechanics shown above the cards (if you are premium) will be scalated to fit the size of the cards. So they will look good on a 4k screen.

- List of cards shown in the different tabs of AT that you need to track while you play HS. This cards don't scale automatically but you can define their size in the config tab --> Deck --> Card slider.
Its default value is 35 px and the maximum value of this slider is defined by the resolution of your screen, in my 1080p screen the max value is 50 px, in a 4k screen will be much higher.

Let me know if this helps or if you have any other question.
Triodo

**Comment by jvook** [comment]
Yeah but all of the premium feature tabs don't scale either :\

**Comment by supertriodo** [comment]
Sorry I'm a little lost without being able to properly test it on my screen.
Could you send me some screenshots in 4k with the elements that don't scale correctly?

All important things I think now should scale like draft overlay, cards and replay. Only buttons, tabs and slider should see tiny.

**Comment by jvook** [comment]
I'm not supporting on patreon right now because everything was too small,
so I can't take the screenshots.  The arenatracker window is 1/4 size at 4k
compared to 1080p.  All of the elements are 1/4 size.. deck list, replays
etc.  Expanding the window doesn't increase the scale of anything so it's
all tiny.  The only thing that scales are the draft overlay with scores,
synergies, etc.  Nothing in the main window.

**Comment by jvook** [comment]
Here are the screenshots I could get: https://imgur.com/a/ksqlGsg

**Comment by supertriodo** [comment]
List of cards shown in the different tabs of AT that you need to track while you play HS. This cards don't scale automatically but you can define their size in the config tab --> Deck --> Card slider.
Its default value is 35 px and the maximum value of this slider is defined by the resolution of your screen, in my 1080p screen the max value is 50 px, in a 4k screen will be much higher.

**Comment by jvook** [comment]
I know it looks fine on a 1080p screen but on the real screen the card list
is too small to read.  I'll get another screenshot showing small text and
also distortion from my surface pro.

**Comment by supertriodo** [comment]
On 4k move the cards slider all the way to the right and send me a
screenshot of a deck list so I can see whats the problem with the cards

**Comment by jvook** [comment]
Yeah I tried it out and the card size slider also scales the list items.  I
really didn't expect this because it says card size.  Maybe it's just me
but since it scales more than cards maybe it could be called "UI Scale" or
something like that.  Thanks for the help.
