### ISSUE TITLE
AppImage on Debian Buster crashes upon draft

### ISSUE THREAD

**Issue by CharString** [supertriodo/Arena-Tracker#116]
`terminate called after throwing an instance of 'QUnhandledException'
  what():  std::exception
`
If I scroll a bit further up I see
`OpenCV Error: Unsupported format or combination of formats (type=0
) in buildIndex_, file /home/triodo/opencv-2.4.13.5/modules/flann/src/miniflann.cpp, line 315
`

I also built the release target from source (after building the 2.4 branch of opencv from source), same crash, same OpenCV Error. I couldn't get the debug target to build. I hope this gives enough pointers to people familiar with the codebase.

**Comment by pulkin** [comment]
Same error with Fedora 33.

**Comment by Mistra** [comment]
Have a look at #132 . Do you use Wayland? Does it work with Xorg?

**Comment by CharString** [comment]
I was using Xorg.
