### ISSUE TITLE
Request: Option to disable the crowns around the highest score cards

### ISSUE THREAD

**Issue by jvook** [supertriodo/Arena-Tracker#117]
It makes me overvalue cards simply because of the visual even if it's 106 vs. 108. Would it be possible to add an option to disable those graphics?

**Comment by supertriodo** [comment]
![image](https://user-images.githubusercontent.com/8259393/106898888-08777800-66f5-11eb-97d7-9702ed8b2c0d.png)
![image](https://user-images.githubusercontent.com/8259393/106899056-32309f00-66f5-11eb-8b90-a381f796762f.png)

**Comment by jvook** [comment]
Thanks
