### ISSUE TITLE
Can't display over hearthstone in fullscreen mode, Xubuntu 18.04

### ISSUE THREAD

**Issue by ConnahGriffin** [supertriodo/Arena-Tracker#118]
I set the window to be always on top, it still doesn't display over the game if it is on fullscreen.

I'm at a lost for what to do, could this be a bug?

I it is, what would you require to check the state? I'm fairly new to linux, I don't know what I should be doing. Just say it and it shall be done to the best of my capabilities.

**Comment by supertriodo** [comment]
https://www.reddit.com/r/ArenaTracker/comments/fyhdj4/cant_display_over_hearthstone_in_fullscreen_mode/
