### ISSUE TITLE
[Request] Support all secrets in Wild

### ISSUE THREAD

**Issue by Neonate14** [supertriodo/Arena-Tracker#119]
I know this tracker is for Arena, but it's the only good tracker on Linux and it works very well in Constructed. The main issue is that it doesn't consider Wild-only Secrets in the hand window (Ice Block for example). 

It would be great if there was a setting that allows the bot to consider Wild-only secrets.

**Comment by Neonate14** [comment]
Also, there's a weird bug in Paladin secrets in Wild. The tracker shows the Paladin secrets fine but adds an entry for a Hunter Secret (Pack Tactics) in the hand window.
I'm not sure If I should report this as a separate bug, but I guessed it's probably related to Wild not being supported.

**Comment by supertriodo** [comment]
Thanks for the feedback.

There was indeed a bug that showed pack tactics as a paladin secret in constructed modes (standard and wild). It's fixed in the new v8.15.

I have added a new feature to show wild secrets, it's in the premium version of AT.

AT v8.15 is already out.
