### ISSUE TITLE
deck import

### ISSUE THREAD

**Issue by Trskldn** [supertriodo/Arena-Tracker#12]
Thank you for Arena Tracker.
How can i import deck from hearthstone in to Arena Tracker?

**Comment by supertriodo** [comment]
There are three ways:

1) The easy way. AT automatically fill your deck while you play, so just start playing, after you finish your first game you can update the number in every card to help building the deck. Remember to save the deck in AT decks before leaving this way you will have it for next time.

2) The tricky way. Replace two different cards from your deck for 2 fel reavers. Play in practice mode and mulligan for your fel reavers. When played the fel reavers will go over your whole deck as it discards cards.

3) The building way. Using the New deck --> Import HearthHead deck, in the deck window. Go to HearthHead and create the deck in your account using their [deck builder](http://www.hearthhead.com/deckbuilder). When you are done, you will be able to use the export--> cockatrice option to create the deck in AT.

**Comment by supertriodo** [comment]
Update for method 3:
HearthHead no longer let you export--> cockatrice.
I suggest you using HearthPwn.
