### ISSUE TITLE
User guide link doesn't work (404)

### ISSUE THREAD

**Issue by Ka-hu** [supertriodo/Arena-Tracker#121]
https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/

This is broken. Please fix the link to the docs.

**Comment by supertriodo** [comment]
Thanks for the heads-up. The old gitbook interface has been deprecated. I've moved to the new gitbook system.

Here is the new user guide: https://triodo.gitbook.io/arena-tracker-documentation/en

I'm still reviewing it so some links might be broken.
