### ISSUE TITLE
Deck tracker retains extra cards generated in deck

### ISSUE THREAD

**Issue by jvook** [supertriodo/Arena-Tracker#123]
e.g., using Deck of Lunacy will cause the tracker to retain any spells drawn that were generated by Deck of Lunacy, even into a new game where the cards are no longer in the deck.
![extracards](https://user-images.githubusercontent.com/17225171/105385785-b9542200-5be1-11eb-82da-a611ada3aa9f.jpg)

**Comment by supertriodo** [comment]
I'll look into it, thx!

**Comment by supertriodo** [comment]
Ready for next release. You need to have your deck list loaded on AT and AT won't identify the generated ones with the old ones on your deck, so after playing Deck of Lunacy the deck tab won't show any more card as drawn.
