### ISSUE TITLE
UI becomes distorted after starting a new arena run

### ISSUE THREAD

**Issue by jvook** [supertriodo/Arena-Tracker#124]
The UI consistently gets distorted after starting a new Arena run, and doing nothing but playing hearthstone.  It requires a restart of the app to fix.
![distortedui](https://user-images.githubusercontent.com/17225171/105386094-ff10ea80-5be1-11eb-8997-12d4accb6c6e.png)

**Comment by supertriodo** [comment]
When this happens I recommend using the force draft button at the top of config tab. It forces AT to look for the frame of arena again.

**Comment by Npaffen** [comment]
[Screenshow](http://prntscr.com/xxpjot). 
I tried to force draft option but it did not work. Restart seems not to help either. Any idea how to fix this?

Best regards.

**Comment by supertriodo** [comment]
Hi @Npaffen , your case it's different, AT is finding the frame correctly, see how the scores are correctly located under the cards. 

In your case the problem is that AT is not identifying correctly the 3 picks. In your screenshot the colors of your screen looks too brown, no idea why.

**Comment by supertriodo** [comment]
You can try to remove the dir (USER/Arena Tracker/Hearthstone Cards) and restart AT to force it to download all HS cards again.

You can also change the cards selecting from the drop-down list. The list will be filled with other cards with similar colors.

**Comment by supertriodo** [comment]
[This commit](https://github.com/supertriodo/Arena-Tracker/commit/77eb80e4041815ee2d237656b44db352a9b3a9bb) will avoid some bad framing in the future.
