### ISSUE TITLE
scores are not visible.

### ISSUE THREAD

**Issue by D33M0N** [supertriodo/Arena-Tracker#126]
there is 0 visible scores on the screen after last update to AT.
the window "AT Scores" is on panel, it's also always on top, but it must be transparent?

**Comment by supertriodo** [comment]
lightforge has been removed from AT. do you have any other assistant, ha or hsr, enabled on config tab?

**Comment by D33M0N** [comment]
no idea what "lightforge" is. or "ha" or "hsr". never really touched the config tab as it's so confusing. just swapped theme and and changed transparency.
![image](https://user-images.githubusercontent.com/15782020/107144271-c6dc0c80-6942-11eb-940a-5f5a499ee155.png)

**Comment by supertriodo** [comment]
https://triodo.gitbook.io/arena-tracker-documentation/en/config-tab#draft
