### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by roboserg** [supertriodo/Arena-Tracker#127]
Does not detect the game at all, tried running as admin or not, latest release, ver 9.3.

Tried running HS windowed and full screen, restarting the app or the game. Nothing. Win10.

https://i.imgur.com/uZp5Q5g.jpg

**Comment by supertriodo** [comment]
Read this:
https://triodo.gitbook.io/arena-tracker-documentation/#i_setup_the_app_but_it_doesnt_work_it_didnt_upload_my_arena_game_it_didnt_start_drafting

**Comment by roboserg** [comment]
> Read this:
> https://triodo.gitbook.io/arena-tracker-documentation/#i_setup_the_app_but_it_doesnt_work_it_didnt_upload_my_arena_game_it_didnt_start_drafting

Thanks. I managed to get the app to detect the game but then it got stuck at downloading the cards, first at "CORE_EX1_169". I killed the app, restarted as admin and now its at "downloading cards..."

https://i.imgur.com/ZWtulvl.png

**Comment by supertriodo** [comment]
It shouldn't need admin access.

**Comment by supertriodo** [comment]
Keep in mind with today patch some things can be broken, I am keeping an eye on things.

**Comment by roboserg** [comment]
> It shouldn't need admin access.

I am trying with both, it is stuck at "downloading cards"  and it doesn't download it judging by the task manager

**Comment by supertriodo** [comment]
You can extract the exe and put it wherever you want, that dir was autocreated with the same name of the zip.

The fact that its trying to download CORE_EX1_169 means there is something wrong in the new patch. I need to look at it. The problem is not in your end.

**Comment by roboserg** [comment]
Right now it gets stuck at "downloading cards...", not CORE_EX1_169 anymore. Does the app work for you right now after the patch?

**Comment by supertriodo** [comment]
It works for people who don't need to download the cards. If you are starting for first time or after some weeks of last use it will try to download all the cards and fail.

**Comment by supertriodo** [comment]
I can give you a dirty trick while I fix it tomorrow. 
Go to AT dir/Extra and remove cards.json
Download this https://api.hearthstonejson.com/v1/26757/enUS/cards.json
and put it on AT dir/Extra with the name cards.json

**Comment by supertriodo** [comment]
Correct download this file:
https://api.hearthstonejson.com/v1/26757/all/cards.collectible.json

**Comment by supertriodo** [comment]
Correction download this:
https://api.hearthstonejson.com/v1/26757/all/cards.json

**Comment by supertriodo** [comment]
Download this instead
https://api.hearthstonejson.com/v1/26757/all/cards.json
AT dir is on USER/Arena Tracker/

**Comment by roboserg** [comment]
> Download this instead
> https://api.hearthstonejson.com/v1/26757/all/cards.json
> AT dir is on USER/Arena Tracker/

Thanks, it works now! May I suggest using /user/AppData or the .exe folder for the settings, not the `USER/Arena Tracker/`
Normally the /user/ folder on Windows is only for Windows folders, not user data

**Comment by supertriodo** [comment]
You can have it with the exe.
https://triodo.gitbook.io/arena-tracker-documentation/#i_dont_want_arena_tracker_dir_messing_around_in_my_home_dir

**Comment by supertriodo** [comment]
That cards.json is too old. Looking farther you should use this:
https://api.hearthstonejson.com/v1/74257/all/cards.json
