### ISSUE TITLE
Windows follow mouse without click

### ISSUE THREAD

**Issue by vince** [supertriodo/Arena-Tracker#13]
Strange issue.. but sometimes when I use this app (Ubuntu Linux 16.04) the windows follow my mouse even though I haven't clicked on them. That means if I move my mouse over the deck tracker and it follows my mouse as if I'm trying to reposition it. It happens across 2 different computers.

I'm uncertain how to reproduce this consistently but I'd be happy to look into it if you can point me the right direction.

**Comment by supertriodo** [comment]
In the code AT only moves while the left button is pressed. Maybe is a bug related to Unity, the DE of Ubuntu.

**Comment by vince** [comment]
I'm using Gnome on two laptops with touchscreens, but yes possible it's not related to your code directly. I haven't seen this behavior on other apps but then again I don't use other apps as often as I use your deck tracker. :)
