### ISSUE TITLE
app crashed on mac

### ISSUE THREAD

**Issue by akahanaton** [supertriodo/Arena-Tracker#130]
hi,

The app crashed every time when I enter the arena with error:

```
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /Users/mingwen/Downloads/opencv-2.4.11/modules/core/src/matrix.cpp, line 323
libc++abi: terminating with uncaught exception of type cv::Exception: /Users/mingwen/Downloads/opencv-2.4.11/modules/core/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat
```

Do you have any solution, thank you very much.

**Comment by supertriodo** [comment]
No, sorry.
This is not the first time I see this error.

**Comment by akahanaton** [comment]
oh, so sad, thank you all the same

**Comment by akahanaton** [comment]
Hi, i build the app by myself, here is the full error info:

`17:51:57 - GameWatcher(13): LoadingScreen: GAME_MODE -> DRAFT
17:51:57 - GameWatcher(13): Entering ARENA (loadingScreenState = arena).
17:51:57 - DeckHandler: Enter arena
17:51:57 - DraftHandler: Hearthstone arena screen loaded from settings.
17:51:57 - DraftHandler: Create heroDrafting windows.
qt.qpa.cocoa.window: Window position outside any known screen, using primary screen
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /Users/mingwen/Downloads/opencv-2.4.11/modules/core/src/matrix.cpp, line 323
libc++abi: terminating with uncaught exception of type cv::Exception: /Users/mingwen/Downloads/opencv-2.4.11/modules/core/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat`

any idea? thanks a lot

**Comment by supertriodo** [comment]
It's gonna be difficult without been able to reproduce it myself.

If you have programming background you could try to debug it with qt + gdb and find the exact point where is crashing and the reason.

With that I might investigate further and fix it in the code.
