### ISSUE TITLE
v10 AppImage just fails to start

### ISSUE THREAD

**Issue by D33M0N** [supertriodo/Arena-Tracker#133]
```
[deemon@Zen Applications]$ ./ArenaTracker.Linux.AppImage 
./ArenaTracker.Linux.AppImage: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full
```

**Comment by supertriodo** [comment]
Maybe this can help.

https://bbs.archlinux.org/viewtopic.php?id=269838

**Comment by D33M0N** [comment]
I got the impression that "AppImage" as such, should have this covered. Whatever the app needs, in whatever version, is included in the AppImage itself. No? :-)

**Comment by supertriodo** [comment]
Maybe try the static version from AUR?

https://aur.archlinux.org/packages/arenatracker-bin/

It seems a little outdated though.

**Comment by D33M0N** [comment]
I am a little bit confused about what you are trying to do here... I thought this is like bug reporting place for developer to actually get information about bugs and for him fixing them hopefully. Not the place for developer to educate users to work around bugs and try to trick the program to do what it's supposed to do...  :-D

**Comment by supertriodo** [comment]
Yes, but yours is not an AT problem. It's a problem with the libc version running on your distro.

**Comment by D33M0N** [comment]
Isn't the problem that you have not included the correct version in the appimage in the first place?

**Comment by CharString** [comment]
> Isn't the problem that you have not included the correct version in the appimage in the first place?

It's an issue with the AppImage toolchain: AppImage/AppImageKit#1162

**Comment by CharString** [comment]
@supertriodo to be explicit: that thumbs up was me confirming via a mobile github client that the patched version works perfectly on PopOs, a Debian derivative.

**Comment by supertriodo** [comment]
Great thx!
