### ISSUE TITLE
doesnt work at all

### ISSUE THREAD

**Issue by Anvikk** [supertriodo/Arena-Tracker#136]
arena tracker doesnt recognize new arena, have to force draft after choosing class it can recongnize cards but after every single choice i have to click on refresh button to see new cards ranking. and shows only ranking at heartarena not hsreplay. in the game alone it doenst recognize any action just empty windows. does any one have any idea what is possible the cause ? and how to fix it?

**Comment by supertriodo** [comment]
https://triodo.gitbook.io/arena-tracker-documentation/#i_setup_the_app_but_it_doesnt_work_it_didnt_upload_my_arena_game_it_didnt_start_drafting-1
