### ISSUE TITLE
No transparency under Lubuntu 14.04

### ISSUE THREAD

**Issue by EfficiencyVI** [supertriodo/Arena-Tracker#14]
See attached screenshot. 
![transparency](https://cloud.githubusercontent.com/assets/8409366/15824479/aea1801c-2bff-11e6-8ad8-bab7eb7373a4.png)

I'm not sure if this is a common problem with Linux/Ubuntu or if there is a library or something missing.

Also a bit unrealated … I'm no arena player. Is there any way to manage constructed plays like uploading the stats to hearthstats? I made an Arena Mastery account but this site is not really helpful for me.

**Comment by EfficiencyVI** [comment]
I was able to fix it. Maybe someone should add that to the instructions. Lxde has no compositing. You can fix it by doing:

`sudo apt-get install xcompmgr`

and then add xcompmgr to the autostart. Maybe someone has an idea for my second problem. :+1:

**Comment by supertriodo** [comment]
Thanks for your feedback. I'll add the LXDE instructions to the readme.

About managing constructed stats it's not possible at the moment, Arena Tracker was initially created for arena players (like me), that's why I chose Arena Mastery.

**Comment by EfficiencyVI** [comment]
Hm, than you! Do you plan to play more constructed? :-D

I really like your tracker but the use of it in constructed plays is really limited as you cannot e. g. track the winrates of a deck over a longer time. And there are no other trackers that run on non Windows PCs.

**Comment by supertriodo** [comment]
Have you tried Trackobot? It works along with AT.

**Comment by EfficiencyVI** [comment]
Thank you for your reply. Track-O-Bot is IMHO not very good. Newer versions conflict with Arena Tracker because it changes the log.config format and from everything I have seen it is just incredible buggy. It took me almost an hour just to make it compile.
