### ISSUE TITLE
Arena-Tracker is killing my internet

### ISSUE THREAD

**Issue by Ninehills42** [supertriodo/Arena-Tracker#140]
Hello,

Whenever I start the Arena-Tracker app, it starts to kill my internet connection immediately (Im using WiFi at home)

![image](https://user-images.githubusercontent.com/47057882/206247169-0c6c9e2f-8893-4a37-b390-f7c8e100de7b.png)
Using -ping IP -t (I happened to use the IP of overwatch.com, doesn't matter), the first timeout you see is when the app launches, and when the last timeout happened my wifi got completely disconnected from my router.

This pattern happens any time I start Arena-Tracker.

**Comment by supertriodo** [comment]
Try using the prev version: https://github.com/supertriodo/Arena-Tracker/releases/tag/v22.11

I increased the number of cards downloaded at the same time and that might be the issue.

**Comment by supertriodo** [comment]
New v22.12.01 have the changes to card downloading reversed. Let me know if that solves you problems.
