### ISSUE TITLE
Secret tracker does not show full list of secrets in wild

### ISSUE THREAD

**Issue by Kangaroux** [supertriodo/Arena-Tracker#145]
For mages it shows 5 secrets in wild:
- Ice barrier
- Explosive runes
- Counterspell
- Objection
- Vengeful Visage

Not sure if this is exclusive to only mages or wild

**Comment by supertriodo** [comment]
Did you have the show wild secrets checkbox in option tab?

At doesnt know if yoy are playing wild or standard.

**Comment by Kangaroux** [comment]
@supertriodo I don't see that option, using the latest AppImage for linux

![image](https://github.com/supertriodo/Arena-Tracker/assets/2302541/51f876ef-0cbb-4e08-a584-48ab4e1a0a86)

**Comment by supertriodo** [comment]
Its in the premium version
