### ISSUE TITLE
Moving to opencv 3?

### ISSUE THREAD

**Issue by Erotemic** [supertriodo/Arena-Tracker#15]
I'm wondering if there is any intention on moving towards opencv 3.0? 
I have experience with computer vision, and if there is I would be willing to help out.
Is utility.cpp / utility.h the only place that would need update?

**Comment by supertriodo** [comment]
Used in Utility and DraftHandler. Upgrading to 3.0 is not really a problem of updating the code. I use MXE to crosscompile from Linux to Windows and when I prepared it, it wasn't supporting 3.0

Anyway there's no urge to move to 3.0
