### ISSUE TITLE
how come stats disagree from HSR when looking directly on site?

### ISSUE THREAD

**Issue by mutsurhea** [supertriodo/Arena-Tracker#151]
![image](https://github.com/supertriodo/Arena-Tracker/assets/77935124/a4457165-b7c3-4241-bca4-b450e72434af)
![image](https://github.com/supertriodo/Arena-Tracker/assets/77935124/8dab6ec8-017f-4587-be48-74d5e68682d9)

**Comment by supertriodo** [comment]
HSR stats are download to your disk once a day.
