### ISSUE TITLE
Deck creating don't work with localized version of Hearthstone

### ISSUE THREAD

**Issue by VitalD** [supertriodo/Arena-Tracker#16]
I use Russian language as language of Hearthstone and Arena Tracker works well, but deck creating don't work, Tracker input nothing into search line and try to add wrong cards several times.

**Comment by supertriodo** [comment]
This is a known bug of pyAutoGUI, a python library used by Arena Tracker for the deck creating. It will only work correctly when using an US keyboard.

Thanks for you feedback though.
