### ISSUE TITLE
Display bug in Linux version 4.0

### ISSUE THREAD

**Issue by EfficiencyVI** [supertriodo/Arena-Tracker#17]
When I open the new Game plan tab and press on swap size I end up with two start tabs. See attached screenshot.
![arena tracker](https://cloud.githubusercontent.com/assets/8409366/16548014/523036ca-4180-11e6-8260-7f1d72d535e6.png)

**Comment by supertriodo** [comment]
I have been able to reproduce the problem, while I fix it you can uncheck "split window" in config tab to avoid this bug.

Thanks for the feedback.

**Comment by supertriodo** [comment]
I have fix the problem. To be sure before releasing a new version, can you test it? Remember to check the split window option, the bug only appeared with it on.

https://drive.google.com/open?id=0B7S6qjtH-56hM0ZSTlRzQzBaWWM

**Comment by EfficiencyVI** [comment]
Thank you! It seems to work fine. :+1:

**Comment by Strit** [comment]
So, 4.1 releasing soon?
Just so I know when to update the AUR package for Arch Linux. :)

**Comment by supertriodo** [comment]
Yes, really soon

**Comment by supertriodo** [comment]
Fixed in [v4.0.1](https://github.com/supertriodo/Arena-Tracker/releases/tag/v4.0.1)
