### ISSUE TITLE
Won matches are tracked as lost (fixed) / Missing UI Elements, V4.0.2 not starting

### ISSUE THREAD

**Issue by EfficiencyVI** [supertriodo/Arena-Tracker#18]
See attached screenshot I cannot explain when or why this happens but e. g. yesterday I climbed 3 ranks with a 6-19 deck (according to Arena Tracker).

![but](https://cloud.githubusercontent.com/assets/8409366/16901332/a34c4736-4c40-11e6-90f6-d278cc3f2411.png)

**Comment by supertriodo** [comment]
Which version are you using? [4.02](https://github.com/supertriodo/Arena-Tracker/releases/tag/v4.0.2) fixed the [loses bug](https://www.reddit.com/r/ArenaTracker/comments/4slz8c/wins_registered_as_losses/) introducid by the last HS patch.

**Comment by EfficiencyVI** [comment]
Okay, I had to update. Suggestion: can we have a version number and maybe a check for newer versions in the tracker? I looked if someone filed an issue here but not if someone posted something on reddit. Thank you for the quick fix.

**Comment by supertriodo** [comment]
Wait, there's suppose to be working an update advisor, it doesn't auto-update, but AT should notify you when a new version is available for download. Is it working for you?

Also in the log tab (that is shown in split mode when the main window shows at least two segments) appears the actual version and the newest version.

**Comment by EfficiencyVI** [comment]
No, the button is always greyed out. There is also no second log tab 

![but1](https://cloud.githubusercontent.com/assets/8409366/16901690/dcdfb190-4c4a-11e6-9859-9f6312e5466b.png)
![but2](https://cloud.githubusercontent.com/assets/8409366/16901691/dce7fabc-4c4a-11e6-82e3-519bc2e57d81.png)

When I start version 4.0.2 I get this error:

`ArenaTracker: relocation error: ArenaTracker: symbol _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference`

Versions before worked fine.

**Comment by supertriodo** [comment]
Ok, it seems the notice advisor for new version is not working, I'll take a look.
Regarding the library error has to be something to do with an old version of the library, you probably need to update to a newer version, I'll take a look too.

**Comment by EfficiencyVI** [comment]
https://forum.juce.com/t/projucer-not-running-on-14-04-lts/15972/15 <- this seems to be a problem with Ubuntu 14.4 LTS. I will keep running 4.0.0.1 and look on Track-O-Bot now for real statistics. :-(

**Comment by supertriodo** [comment]
My library version on Linux Mint 18 is libstdc++.so.6.0.21

**Comment by sit0** [comment]
Same here on LTS 14.4. Triodo, why not link it statically with libstdc++?

**Comment by supertriodo** [comment]
Is such a common library that shouldnt be necessary. I'll take a look to add it, but shouldn't you already be on 16.04? :)

**Comment by sit0** [comment]
I tend to like Ubuntu less with every release. Thinking of Arch, but I'll give Mint a try. Maybe next weekend.

**Comment by EfficiencyVI** [comment]
@supertriodo Ubuntu LTS 14.04 is supported until 2019

http://www.ubuntu.com/info/release-end-of-life

**Comment by supertriodo** [comment]
It doesn't seem trivial to statically compile with libstsc++

Have you guys tried to update to the latest version?

**Comment by supertriodo** [comment]
Is 4.0.1 failing too?

**Comment by sit0** [comment]
4.0.1 works fine

**Comment by supertriodo** [comment]
These are my library, paste them (at your own risk) on /usr/lib/x86_64-linux-gnu

[libstdc++.zip](https://github.com/supertriodo/Arena-Tracker/files/368024/libstdc.zip)

**Comment by supertriodo** [comment]
If 4.0.1 works fine the problem comes from updating my machine to Linux Mint 18 and building from the new setup.

**Comment by sit0** [comment]
And yes, tried adding current build repos and upgrading libgc++, no luck :(

**Comment by supertriodo** [comment]
No more references to libstdc++ in ldd, please tell me it works.

[ArenaTracker static libstdc++.zip](https://github.com/supertriodo/Arena-Tracker/files/368085/ArenaTracker.static.libstdc.zip)

**Comment by sit0** [comment]
Works like a charm :)

**Comment by supertriodo** [comment]
Great!

**Comment by supertriodo** [comment]
Eficiency, about the update button greyout, that button is to refresh your arena results from arena mastery, if is greyout is because you havent entered an account. 

The update message should appear when starting AT with an old version, now it's not working because I messed up with my version naming, It will work again for next release.

**Comment by supertriodo** [comment]
Fixed from 4.03

**Comment by EfficiencyVI** [comment]
I updated after the tracker told me there was an update. Good work! Thank you! :+1:

**Comment by supertriodo** [comment]
;)
