### ISSUE TITLE
Change libpng12 dependency to libpng?

### ISSUE THREAD

**Issue by Strit** [supertriodo/Arena-Tracker#19]
Is it possible to change the libpng12 dependency to libpng?

Libpng12 is getting really old.

**Comment by supertriodo** [comment]
Is a dependency of opencv (the version I'm using is pretty old). I'll have to update at some point.

**Comment by Strit** [comment]
Oh okay.

I'm the maintainer of the AUR package, and the libpng12 package is also an AUR package, while libpng is in regular repositories.

That's my reason for asking. But thanks for the answer.
