### ISSUE TITLE
Feature request: do not reset after a deco/reco…

### ISSUE THREAD

**Issue by soli** [supertriodo/Arena-Tracker#20]
Hi,

thanks for the great app.

I noticed a few times that if my Hearthstone app crashes (I'm on a Mac in case it matters) and I manage to run it again and resume, ArenaTracker resets at some point during the HS loading phase, just before I do resume my game.

No idea if it is easy to recognize this type of scenario from the logs, but it would be great if ArenaTracker could detect that when a game was not finished, it might be resumed…

**Comment by supertriodo** [comment]
That's the normal behaviour of AT. I take note of your request. Does it crash so often to be a problem?

**Comment by soli** [comment]
Well, let's just say that the MacOS client is not as stable as it should ;)
Yesterday I experienced for the first time a graphical bug that I had seen reported quite often, and not long after, the client crashed.

I wouldn't say it is very frequent, so there is definitely no huge priority here, but since the HS client crashes from time to time, that would be nice if AT could handle it…
