### ISSUE TITLE
Issues with Karazhan cards

### ISSUE THREAD

**Issue by vaidab** [supertriodo/Arena-Tracker#21]
I had a choice with Ivory Knight in the middle and no scores were shown. I finally chose the Knight and it was added to my deck as a 0 mana card.
Screenshot: https://i.imgur.com/7fn8DCt.png

**Comment by supertriodo** [comment]
Karazhan cards will come soon. On holidays right now.

**Comment by supertriodo** [comment]
Ready on v4.1
