### ISSUE TITLE
libjpeg8 dep

### ISSUE THREAD

**Issue by tonyrh** [supertriodo/Arena-Tracker#23]
Hi, it looks like libjpeg8 is being phased out of Debian. I'm on Stretch (testing) and the package is already removed, so it won't be in the next stable release. I don't know about Ubuntu, but I think libjpeg-turbo is in their repos as well. Could you link to libjpeg-turbo instead?

**Comment by supertriodo** [comment]
It's a dependency of opencv. I'll have to consider changing to the latest opencv version.

**Comment by Mutisk** [comment]
If you change opencv, please also consider alternatives to SIFT and SURF which are encumbered by patents/royalty fees.

**Comment by supertriodo** [comment]
If libjpeg is still an issue I can statically linked it in the linux build.
