### ISSUE TITLE
Can't keep Arena-Tracker on top

### ISSUE THREAD

**Issue by verthrix** [supertriodo/Arena-Tracker#24]
Even starting HS minimized and alt+tabbing into it later doesn't help.
I run Arch Linux with KDE
HS is ran through POL with vanilla install plus overrides:
api-ms-win-crt-runtime-|1-1-0 (native, builtin)
api-ms-win-crt-stdio-|1-1-0 (native, builtin)
ucrtbase (native, builtin)
vcruntime140 (native, builtin)
(necessary for battle.net to work)
Arena-Tracker stays only on top in true windowed mode
Disabling composition just turns off transparency, and selecting "Keep it below others" option for HS window simply prevents me from being able to alt+enter into fullscreen

**Comment by supertriodo** [comment]
Not much else can be done. You can play on windows mode, that's the way I actually use it in Linux Mint.
