### ISSUE TITLE
Joust adds a temporary card to deck

### ISSUE THREAD

**Issue by pathmann** [supertriodo/Arena-Tracker#26]
If your opponent plays a card with joust (seen with Kings Elekk and Master Jouster), a temporary card is shown in my deck. It's purple and just says "by Kings Elekk".

I'm not quite sure, if the card shown by the joust is replaced by this card in the decklist, or if it's an additional temporary card. I'll report  back.

I haven't tested if that also happens, if I play a card with joust.

**Comment by supertriodo** [comment]
Noted, thx!

**Comment by supertriodo** [comment]
Fixed on [v4.11](https://github.com/supertriodo/Arena-Tracker/releases/tag/v4.11)
