### ISSUE TITLE
Make the "Arena Tracker" directory a hidden directory in Linux

### ISSUE THREAD

**Issue by TLATER** [supertriodo/Arena-Tracker#27]
For people who care about structure leaving random directories everywhere is incredibly bothersome, especially when it is their home directory.

Could this be moved to either ".Arena Tracker" or one of the many hidden configuration/app data directories, e.g. .local, .config or .share?

Alternatively a configuration file that can specify the location of the directory if present could be a solution to keep it backwards compatible, e.g. .config/arenatracker.

**Comment by supertriodo** [comment]
In the FAQ:

* I don't want an Arena Tracker dir messing around in my HOME dir!
 * If you don't want Arena Tracker dir in your HOME dir, you can place it wherever you want and move Arena Tracker binary to the same place and Arena Tracker dir won't be created in your HOME anymore.

**Comment by TLATER** [comment]
That does not work when using the arch AUR package, since it places the binary in /usr/bin, where binaries are supposed to go.

Having binaries in user directories seems misstructured to me as well.
