### ISSUE TITLE
Doesn't cycle to the next card in Arena

### ISSUE THREAD

**Issue by weirddan455** [supertriodo/Arena-Tracker#29]
I select my class in Hearthstone then pick the class in Arena Tracker.  It correctly recgonizes my cards but then when I select one, it doesn't move on to my next choices.  The cards in Arena Tracker are still showing the cards from the last selection that I already chose.  The only way to fix it is to go re-select my class in Arena Tracker but then it doesn't even build my deck.  This app is basically unusable for me.

I'm on Arch Linux fully updated running XFCE.  Hearthstone running in Windowed mode because I don't have the "Alt+Enter" function like Mint and when I do full screen it hides Arena Tracker.

**Comment by supertriodo** [comment]
Check the [FAQ](https://github.com/supertriodo/Arena-Tracker#faq)

Question:
I setup the app but it doesn't work/ it didn't upload my arena game/ it didn't start drafting.

**Comment by weirddan455** [comment]
I did read the FAQ but it didn't have a solution to my problem.  I think the issue is that the overlay with the rating numbers (directly below the card choices) takes focus away from Hearthstone so when I select my first card, it loses focus and doesn't recognize the next set of choices.  The overlay and the other window continue to show my last choices.

**Comment by weirddan455** [comment]
Here I made a video of the problem:

https://youtu.be/UIELL_stY5M

**Comment by weirddan455** [comment]
It's also not logging my ranked decks or results of my game.  Basically, I can't get this app to do anything besides tell me the 1st card to pick in Arena.

**Comment by supertriodo** [comment]
This usually means Hearthstone is not writting in its log. Which means you didn't setup the paths of Logs dir and log.config correctly. Reset the app (ctrl+r) and [locate](https://github.com/supertriodo/Arena-Tracker#first-run) them again.


Also check this:
    (Only Linux) Arena Tracker is supposed to be run as a normal user (not root). If you run it as sudo you should remove ~/.config/Arena Tracker/Arena Tracker.conf if it belongs to root, and start Arena Tracker again and set the paths so the config file is recreated with your user as owner.

**Comment by weirddan455** [comment]
I reset the app alread, set Logs dir correctly and deleted and recreated the log.config.  I'm not running as root.  You would obviously know more about what the problem could be but it seems to me that it is reading the logs because it correctly identifies the first Arena draft choice.

**Comment by supertriodo** [comment]
Reading the cards in drafting is done through screen capture, that's why is the only thing working.

Send me the file ~/Arena Tracker/ArenaTrackerLog.txt

**Comment by weirddan455** [comment]
Well I Ctr+R and set the Logs again and it works now.  May have messed up before.
