### ISSUE TITLE
Not working under Fedora 22

### ISSUE THREAD

**Issue by jbkt** [supertriodo/Arena-Tracker#3]
Got this message when I tried to launch the program under Fedora 22:
```
$ ./ArenaTracker 
./ArenaTracker: error while loading shared libraries: libHalf.so.6: cannot open shared object file: No such file or directory
```
libHalf is missing, it was last seen in Fedora 20:
http://rpmfind.net/linux/rpm2html/search.php?query=libHalf.so.6

**Comment by supertriodo** [comment]
Try to install that lib. I don't really know how to install packs in fedora.

**Comment by supertriodo** [comment]
Try installing openEXR package.
http://www.rpmfind.net/linux/rpm2html/search.php?query=OpenEXR&submit=Search+...&system=&arch=

**Comment by jbkt** [comment]
Problem is the lib is not included anymore in fedora packages, an also it was not the only library missing. So what I did is to download the old packeges containing the required librarires, extract and copy the libraries in a "lib" directory, then add them to ` LD_LIBRARY_PATH` and the I was able to launch ArenaTracker. It's working fine, I just add to create the missing *log.config* file and launch Hearstone in windows mode (if not the ArenaTracker stay behind).

Following herethe detailed info if it can help somebody.

Packages I have donwloaded:
````
ilmbase-1.0.3-7.fc20.x86_64.rpm
libjpeg8-8d-3.1.x86_64.rpm
OpenEXR-libs-1.7.1-1.fc18.x86_64.rpm
tbb-4.3-1.20141204.fc22.x86_64.rpm
````

Librairies I have added (with symlinks):
````
libHalf.so.6
libHalf.so.6.0.0
libIexMath.so.6
libIexMath.so.6.0.0
libIex.so.6
libIex.so.6.0.0
libIlmImf.so.6
libIlmImf.so.6.0.0
libIlmThread.so.6
libIlmThread.so.6.0.0
libImath.so.6
libImath.so.6.0.0
libjpeg.so.8
libjpeg.so.8.4.0
libtbbmalloc_proxy.so.2
libtbbmalloc.so.2
libtbb.so.2
````

Launch script:
````
export LD_LIBRARY_PATH=lib:$LD_LIBRARY_PATH
./ArenaTracker
````

**Comment by supertriodo** [comment]
Great! If you have any problem or suggestion let me know.

**Comment by supertriodo** [comment]
Try again in fullscreen. In Linux Mint Arena Tracker works with HS in fullscreen. This is because HS fullscreen is just borderless window.

**Comment by jchristi** [comment]
Fedora 25 user here, I had a similar issue with `libjpeg.so.8`. To get it to work I followed [these instructions](https://ask.fedoraproject.org/en/question/82485/libjpegso8-cannot-open-shared-object-file-no-such-file-or-directory/?answer=82518#post-id-82518).

**Comment by jchristi** [comment]
For anyone coming here in the future, I have a repo for building an RPM to work with Fedora: https://github.com/jchristi/arena-tracker-rpm

**Comment by supertriodo** [comment]
Have you tried the AppImage version of Arena Tracker? It should solve dependencies problems with most of distributions.

**Comment by jchristi** [comment]
I have not. I am not very familiar with AppImage, but I'll look into it.

**Comment by supertriodo** [comment]
Just download the [AppImage version](https://github.com/supertriodo/Arena-Tracker/releases/download/v5.21/ArenaTracker.AppImage) and double click it.
