### ISSUE TITLE
Issue when starting a deck in arena with Ubuntu

### ISSUE THREAD

**Issue by clovisbis** [supertriodo/Arena-Tracker#30]
Since the last update, arena tracker freeze when starting a deck in arena.
When launching Arena tracker with command line i can see :
"wine: Unhandled page fault on read access to 0x00000018 at address 0x495970 (thread 0119), starting debugger..."

**Comment by bwowk** [comment]
You're running it under Wine? There's a Linux native release: [https://github.com/supertriodo/Arena-Tracker/releases/latest]. Try that one instead.

**Comment by supertriodo** [comment]
Yep, no need to use wine.

**Comment by clovisbis** [comment]
Ohhhhh. When I 've downoaded the last update I choose the wrong. I'm very sorry for disturbing.
Thanks a lot.
