### ISSUE TITLE
Automatic upload of games to zerotoheroes

### ISSUE THREAD

**Issue by mmascher** [supertriodo/Arena-Tracker#31]
Hi,

I am a regular AT user and also a regular at http://www.zerotoheroes.com/

I use to record my games with AT, and then upload them to zth by hand. It would be great if it was possible to upload the games directly from AT (like the arenamastery automatic upload)

**Comment by supertriodo** [comment]
I take note, maybe in the future.

**Comment by supertriodo** [comment]
I don't think uploading all the games to zerotoheroes is what the most of the people would use. But I'm working on an easier way of uploading single games from the GUI.

**Comment by mmascher** [comment]
Yes, you are right, I do not want to upload all the games. Just the few I feel like I can get suggestion! Great to hear you are working on that!!!

**Comment by supertriodo** [comment]
Ready on [v4.3](https://github.com/supertriodo/Arena-Tracker/releases/tag/v4.3)

**Comment by mmascher** [comment]
I have just tried this, it works great, thanks!
