### ISSUE TITLE
Arena Mastery login doesn't work

### ISSUE THREAD

**Issue by oittaa** [supertriodo/Arena-Tracker#32]
This is what I see in the logs even though my username and password are correct:

```
16:03:48 - WebUploader: Login Arena Mastery.
16:03:49 - WebUploader: ReplyFinished: signup
16:03:49 - WebUploader: Wrong username or password.
```

**Comment by supertriodo** [comment]
Recheck your information. Confirm that it let you login through the web. Not much else I can do.

**Comment by oittaa** [comment]
Login works through the web as expected. I'm literally just copy&pasting the login and password fields from a password manager. There's not that much that I can recheck.

Are there some debug flags I could enable?

Application version is the latest 4.2.

**Comment by oittaa** [comment]
OK, I figured out what's wrong by capturing some packets with Wireshark.

You're decoding the input for some reason. I had to change a plus sign to `%2B`.

**Comment by supertriodo** [comment]
I'll check out the problem with symbols. Thx for the feedback.

**Comment by supertriodo** [comment]
I revisited my code and the encoding is done properly but it seems there's an exception for the symbol '+', so it needs to be encoded manually. Congratulation you found the only character which would fail ;)
Here's the explanation from Qt docs:



**Handling of spaces and plus ("+")**

Web browsers usually encode spaces found in HTML FORM elements to a plus sign ("+") and plus signs to its percent-encoded form (%2B). However, the Internet specifications governing URLs do not consider spaces and the plus character equivalent.

For that reason, QUrlQuery never encodes the space character to "+" and will never decode "+" to a space character. Instead, space characters will be rendered "%20" in encoded form.

To support encoding like that of HTML forms, QUrlQuery also never decodes the "%2B" sequence to a plus sign nor encode a plus sign. In fact, any "%2B" or "+" sequences found in the keys, values, or query string are left exactly like written (except for the uppercasing of "%2b" to "%2B").
