### ISSUE TITLE
Fetch HearthstoneJSON files on bootstrap/build

### ISSUE THREAD

**Issue by jleclanche** [supertriodo/Arena-Tracker#33]
Rather than storing the json files in git, I recommend you fetch them when bootstrapping the project.

You can directly query this URL: 

https://api.hearthstonejson.com/v1/latest/all/cards.json

This way, you don't have to deal with all the different locales either, you'll just be using an "all locales" file. It'll reduce the app size as well.

**Comment by supertriodo** [comment]
That seems really useful. I'll add it to my todo list. Thanks!

**Comment by supertriodo** [comment]
Ready on [v4.3](https://github.com/supertriodo/Arena-Tracker/releases/tag/v4.3)
