### ISSUE TITLE
Joust Mechanics

### ISSUE THREAD

**Issue by nosklo** [supertriodo/Arena-Tracker#34]
When a joust happens, the card revealed from the opponent's deck is not being added to the "opponent deck" tab.

Additionally, when it is the hunter card "King's Elekk", the card draw is actually the same card revealed, but the hand of the opponent still shows some unknown card.

**Comment by supertriodo** [comment]
Thx for your comments. I'm aware of this behavior. These cases need specific programming for them. I'll add them to my todo list and implement it if it doesn't need too much work.

**Comment by supertriodo** [comment]
Not exactly what asked but on [v4.3](https://github.com/supertriodo/Arena-Tracker/releases/tag/v4.3) cards that are not part of enemy's deck but where played by the enemy during the game are shown with purple text.
