### ISSUE TITLE
The tab of enemy hand desapear in the linux version

### ISSUE THREAD

**Issue by nicolasvillavicencio** [supertriodo/Arena-Tracker#35]
Hi first came first, thanks for your hard work with this project its really great to find a deck tracker for linux. My report its about the tab which track the enemy hand and the secrets he plays, about 2 days ago (with the version 4.2 for ubuntu 16.04) its stop of show any activity and this remain in the last version. The log doesn't show any special error, also run the app compiling the source and the console doesn't how any error. Also the tab of enemy deck works fine.
Do you have any other report of this bugs or any ideas of the cause?
[ArenaTrackerLog.txt](https://github.com/supertriodo/Arena-Tracker/files/626004/ArenaTrackerLog.txt)
![screen](https://cloud.githubusercontent.com/assets/11036162/20817571/5b8e7648-b807-11e6-8193-9cda0c4113b6.jpg)

**Comment by EfficiencyVI** [comment]
Same problem here but I guess we'll see an update soon anyway because of the new cards.

**Comment by facedogg** [comment]
I'm seeing the same thing on the Mac client, happy to add my log file if necessary.

**Comment by aungthumoe5** [comment]
I updated to latest v4.3. The issue is still there on Mac client.

**Comment by EfficiencyVI** [comment]
The cards work on Ubuntu but they don't stack sometimes.

![bug](https://cloud.githubusercontent.com/assets/8409366/20831283/8c5daaa0-b884-11e6-8419-54e52008ac8e.png)

**Comment by supertriodo** [comment]
Thx for the info guys. Last HS patch change the way unknown cards structure are presented in HS logs. A fix is on the way.

**Comment by supertriodo** [comment]
As this is quite a radical change, there probably will other bugs we will discover over the week.

**Comment by supertriodo** [comment]
Should be fixed on [v4.31](https://github.com/supertriodo/Arena-Tracker/releases/tag/v4.31)

**Comment by nicolasvillavicencio** [comment]
Works great again in linux, thanks
