### ISSUE TITLE
HSReplay.net support

### ISSUE THREAD

**Issue by jleclanche** [supertriodo/Arena-Tracker#36]
Hey!

I've been writing documentation for HSReplay.net third party app support. Are you interested?

**Comment by supertriodo** [comment]
Sure, we will talk about it as soon as I finished some stuff I have unfinished.
Thx for the info!

**Comment by Greyvend** [comment]
Is there any news regarding HSReplay.net support? It would be a really nice feature.

**Comment by supertriodo** [comment]
No news, sorry.

**Comment by jleclanche** [comment]
If someone wants to try their hand at it, please get in touch with me on Discord (https://discord.gg/hearthsim-devs).

Our API docs are here now:
https://github.com/HearthSim/HSReplay.net/wiki/HSReplay.net-API-docs

**Comment by jleclanche** [comment]
If someone wants to try their hand at it, please get in touch with me on Discord (https://discord.gg/hearthsim-devs).

Our API docs are here now:
https://github.com/HearthSim/HSReplay.net/wiki/HSReplay.net-API-docs

**Comment by supertriodo** [comment]
Is there anything missing in the next game log or it has everything HSReplay needs?

[ARENA marzo-27 11-44 DRUIDvsSHAMAN WIN.txt](https://github.com/supertriodo/Arena-Tracker/files/872241/ARENA.marzo-27.11-44.DRUIDvsSHAMAN.WIN.txt)

**Comment by jleclanche** [comment]
@supertriodo These are no good, you need to be sending the Power.log file. There's also a lot of metadata you need to be attaching. Ping me on Discord if you need help with it.
