### ISSUE TITLE
jasper library link missing (arena-tracker will not start)

### ISSUE THREAD

**Issue by Monastario** [supertriodo/Arena-Tracker#37]
Hello Everyone,

Can you help me with the following error? 

"arena-tracker: error while loading shared libraries: libjasper.so.1: cannot open shared object file: No such file or directory"

I am using apricityOS and I have jasper installed:

"extra/jasper 1.900.31-1 [installed]"

I am not that experienced with Linux, could you help me with getting the correct symlink or whatever I need to do, please? Any help will be appreciated.

Best Regards,

**Comment by supertriodo** [comment]
In my Linux Mint an ldd on ArenaTracker returns:

libjasper.so.1 => /usr/lib/x86_64-linux-gnu/libjasper.so.1 (0x00007f0566ad0000)

In the software center I have installed
libjasper version 1.900.1-debian1-2.4ubuntu1

Maybe somebody else more linux savy can help you out with this.

**Comment by Monastario** [comment]
When I downgraded to '1.900.5-1' like advised here: https://aur.archlinux.org/packages/arena-tracker/ It works, but I guess it would be better to link the newest one to this libjasper.so.1. I just don't want to break anything.

**Comment by supertriodo** [comment]
I'll try tomorrow to recompile opencv removing libjasper dependencies, Probably is not needed by Arena Tracker.

**Comment by Monastario** [comment]
Thanks, I appreciate your help.

**Comment by supertriodo** [comment]
Try [this](https://drive.google.com/open?id=0B7S6qjtH-56hOE5PQXZ3eVBsYkk) one. It has libjasper statically compiled inside and ldd doesn't show any link anymore. If it works I'll include it in the next release.

**Comment by supertriodo** [comment]
Added in [v4.41](https://github.com/supertriodo/Arena-Tracker/releases/tag/v4.4).
