### ISSUE TITLE
Which Python version do i need?

### ISSUE THREAD

**Issue by chrischtili** [supertriodo/Arena-Tracker#38]
Which Python version do i need?

getting the following results in step 3:
`ChristiansiMac7:~ christian$ sudo pip3 install image
The directory '/Users/christian/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/christian/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting image
  Downloading image-1.5.5.tar.gz
Collecting pillow (from image)
  Downloading Pillow-3.4.2.tar.gz (10.8MB)
    100% |████████████████████████████████| 10.8MB 170kB/s 
Collecting django (from image)
  Downloading Django-1.10.4-py2.py3-none-any.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 282kB/s 
Installing collected packages: pillow, django, image
  Running setup.py install for pillow ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-cjb2k7a5/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-06pdeydm-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    creating build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/__init__.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/_binary.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/_tkinter_finder.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/_util.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/BdfFontFile.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ContainerIO.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/CurImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/DdsImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ExifTags.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/features.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/FliImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/FontFile.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/FtexImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/GdImageFile.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/GifImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/GimpGradientFile.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/Image.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageChops.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageCms.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageColor.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageDraw.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageDraw2.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageEnhance.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageFile.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageFilter.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageFont.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageGrab.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageMath.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageMode.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageMorph.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageOps.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImagePalette.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImagePath.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageQt.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageSequence.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageShow.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageStat.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageTk.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageTransform.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImageWin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/JpegPresets.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/MicImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/MspImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/OleFileIO.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PaletteFile.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PcfFontFile.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PngImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PSDraw.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/PyAccess.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/SunImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/TarIO.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/TiffTags.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/WalImageFile.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.macosx-10.6-intel-3.6/PIL
    running egg_info
    writing Pillow.egg-info/PKG-INFO
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    writing top-level names to Pillow.egg-info/top_level.txt
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    copying PIL/OleFileIO-README.md -> build/lib.macosx-10.6-intel-3.6/PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-cjb2k7a5/pillow/setup.py", line 753, in <module>
        zip_safe=not debug_build(), )
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/private/tmp/pip-build-cjb2k7a5/pillow/setup.py", line 521, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-cjb2k7a5/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-06pdeydm-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-cjb2k7a5/pillow/
`

**Comment by chrischtili** [comment]
i am sure i downloaded Python 3. 
But i have the following result 
ChristiansiMac7:~ christian$ python --version
Python 2.7.10

**Comment by supertriodo** [comment]
You need python 3.

In Mac and Linux python 3 has its own name, so you have to use 

python3 --version

to know your version.

AT uses python3.

**Comment by chrischtili** [comment]
ChristiansiMac7:~ christian$ python3 --version
Python 3.6.0

**Comment by supertriodo** [comment]
It seems there was problems in your installation

"ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting"

Try installing zlib.
