### ISSUE TITLE
New deck buttons disappear

### ISSUE THREAD

**Issue by nicolasvillavicencio** [supertriodo/Arena-Tracker#39]
Hi, I play a couples of arenas and when tries to play other modes the buttons for create and select a new deck disappear . I restart it, reset it , clean the configuration but keep the same. At the moment of start i can see them but a second later disappear and nothing bring them back. Do you have an idea of what can be happening? 

![seleccion_025](https://cloud.githubusercontent.com/assets/11036162/21747426/4a10c8f2-d545-11e6-908e-8245b6557def.png)

and the log doesn't show any weird.

[ArenaTrackerLog.txt](https://github.com/supertriodo/Arena-Tracker/files/691886/ArenaTrackerLog.txt)

The only thing weird was the sync with arena master, because the last game doesn't update, but nothing more.

**Comment by nicolasvillavicencio** [comment]
After restart the pc work again. 
Sorry

**Comment by supertriodo** [comment]
This is because you closed Hearthstone inside the arena menu. Next time you open AT it thinks you are in arena so it hide the deck control buttons. You just need to start HS and when it gets to the main menu AT will show the deck control buttons.
