### ISSUE TITLE
Unable to log in to ArenaMastery with a password containing special characters

### ISSUE THREAD

**Issue by JohnHeroHD** [supertriodo/Arena-Tracker#4]
### Issue:
The application keeps asking me for my arenamastery credentials. First I get the e-mail popup and after that the password popup. And then it goes right back to the e-mail popup. I do not get an error. It just keeps looping.

### Workaround:
Set a new arenamastery password containing only alphanumerical characters.

### Prefered solution:
Accept password containing special characters (like: " * & ^ #, etc.)

**Comment by supertriodo** [comment]
I have tested with the following password ("*&^#) and it works so I will need more info about a test case.

I will close this for now and come back to it if more info/problems appears.

Thanks for the feedback though.

**Comment by supertriodo** [comment]
#32 Found the character that was causing problems '+'
