### ISSUE TITLE
Feture: loading arena tracker

### ISSUE THREAD

**Issue by nicolasvillavicencio** [supertriodo/Arena-Tracker#40]
Hi, recently reinstall arena tracker and test the functionality of automatic discover the logs file in linux, it works perfectly but as suggestion it will be nice a message of "loading arena tracker" because don't show anything even in console so i start to open arena tracker several times, after a while all open at together same time.

Best regards, keep the good work

**Comment by supertriodo** [comment]
I'll add it to my todo list. Thx!

**Comment by supertriodo** [comment]
Added a splash screen during start to let you know Arena Tracker is running.

https://github.com/supertriodo/Arena-Tracker/commit/45dee76b087c26bd697fe339c8c5ce51e9bebd20

Ready for the next release.
