### ISSUE TITLE
qt.network.ssl: QSslSocket: cannot call unresolved

### ISSUE THREAD

**Issue by yoggybeer** [supertriodo/Arena-Tracker#41]
Hi,

I'm using Arena-Tracker with Debian Testing (Stretch) 64bits.
I used 4.2 and it worked fine.
Since I installed 4.41 I have some problems : 
1) At start, I have a lot of error message : 
[...]
`qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
21:09:29 - MainWindow: https://api.hearthstonejson.com/v1/latest/all/cards.json --> Failed. Retrying...
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
21:09:29 - MainWindow: https://raw.githubusercontent.com/supertriodo/Arena-Tracker/master/Extra/importDeck.gif --> Failed. Retrying...
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
21:09:29 - MainWindow: https://api.hearthstonejson.com/v1/latest/all/cards.json --> Failed. Retrying...
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
21:09:29 - MainWindow: https://raw.githubusercontent.com/supertriodo/Arena-Tracker/master/Extra/importDeck.gif --> Failed. Retrying...
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
21:09:29 - MainWindow: https://api.hearthstonejson.com/v1/latest/all/cards.json --> Failed. Retrying...`
[...]

2) It doesn't detect card in Arena (new party to help me to chose the cards); it write "unknown"

3) on the right, every card are shown with a 0 mana and the names don't appear (I think it's related to the 1) problem)

**Comment by supertriodo** [comment]
Arena Tracker (AT) tries to download the hearthstone cards info file (cards.json) from the internet but it fails. That's the reason you see your cards without name or mana.

Googling a bit it seems your QSslSoquet errors are caused by your openssl library.

Maybe you dont have openssl installed. Try this:

sudo apt-get install openssl libssl-dev

**Comment by yoggybeer** [comment]
I already googled it and checked the library :
I have them

Could it be a qt package problem (missing or version) ?

**Comment by supertriodo** [comment]
Qt is statically linked in Arena Tracker binary, so you don't even need Qt installed for it to work.

Maybe is the openssl library version. 

This is my openssl version:

(1.0.2g-1ubuntu4.5)

**Comment by yoggybeer** [comment]
For information:
`$ dpkg -l openssl libssl-dev
[...]
ii  libssl-dev:amd64                               1.1.0c-2                     amd64                        Secure Sockets Layer toolkit - development files
ii  openssl                                        1.1.0c-2                     amd64                        Secure Sockets Layer toolkit - cryptographic utility
`

**Comment by yoggybeer** [comment]
I solved the problem : 
I installed libssl1.0-dev (1.0.2j-4) instead of libssl-dev (1.1.0c-2)

```
$ dpkg -l | grep libssl
ii  libssl1.0-dev:amd64                   1.0.2j-4                             amd64        Secure Sockets Layer toolkit - development files
ii  libssl1.0.2:amd64                     1.0.2j-4                             amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64                       1.1.0c-2                             amd64        Secure Sockets Layer toolkit - shared libraries
```
I suppose we'll have the same problem when 1.0.2 become deprecated in favor of 1.1.0

**Comment by supertriodo** [comment]
Great!
