### ISSUE TITLE
After the patch  7.1 the load deck option has a problem (the origin is api.hearthstonejson)

### ISSUE THREAD

**Issue by nicolasvillavicencio** [supertriodo/Arena-Tracker#42]
Hi just notes that after the last patch when i load a deck from my collection the cards are not correctly load. His name and his mana cost are not appearing.  However when the cards is draw the AT  remove the card normally.
Searching in the log find this line
17:39:37 - MainWindow: https://api.hearthstonejson.com/v1/latest/all/cards.json --> Failed. Retrying...
Actually the service is reporting a 500 error

If you need more info or some help tell me.

**Comment by supertriodo** [comment]
The link to the json works here.

https://api.hearthstonejson.com/v1/latest/all/cards.json

**Comment by nicolasvillavicencio** [comment]
You are right, might be a momentary problem. 

Sorry

**Comment by supertriodo** [comment]
No problem, probably the site got saturated with the new patch.
