### ISSUE TITLE
Consistent Crashes on Mac

### ISSUE THREAD

**Issue by clickety** [supertriodo/Arena-Tracker#43]
The Mac version consistently crashes for me when starting a draft. The ArenaTracker.log and crashlog are attached.
[ArenaTrackerLog.txt](https://github.com/supertriodo/Arena-Tracker/files/816703/ArenaTrackerLog.txt)
[ArenaTrackerMacCrash.txt](https://github.com/supertriodo/Arena-Tracker/files/816704/ArenaTrackerMacCrash.txt)

**Comment by supertriodo** [comment]
Hi,

The main problem is I don't own a Mac to properly test and debug it. I create the binary for Mac through a VM with OS X 10.11 El Capitan. In that VM it works.

If the crash come when starting the draft is probably related to opencv.

There's not much I can do without a real Mac.
