### ISSUE TITLE
Feature Request: Enable import from vicioussyndicate.com x-hearthstone meta tags

### ISSUE THREAD

**Issue by nosklo** [supertriodo/Arena-Tracker#46]
Vicious Syndicate is a well known meta analysis website, it would be nice to be able to import the decks directly into arena tracker.

The HTML content of each deck page contains easily parseable `<meta>` tags with the deck description and each card id, like the example below:

```
<meta property="x-hearthstone:deck" content="Standard Pirate Warrior"/>
<meta property="x-hearthstone:deck:hero" content="HERO_01"/>
<meta property="x-hearthstone:deck:cards" content="OG_312,OG_312,CFM_637,CS2_146,CS2_146,EX1_409,EX1_409,NEW1_018,NEW1_018,CS2_106,CS2_106,CS2_105,CS2_105,OG_315,OG_315,EX1_604,EX1_604,NEW1_027,NEW1_027,NEW1_022,NEW1_022,NEW1_011,NEW1_011,EX1_408,EX1_408,CFM_651,CFM_651,CS2_112,CS2_112,EX1_116"/>
```

Arena tracker could download the html and parse the deck from it if you copy the url of the page and hit the import deck button.

**Comment by supertriodo** [comment]
I'll put it in my TODO list.

**Comment by supertriodo** [comment]
With the [new importing feature](http://eu.battle.net/hearthstone/en/blog/20720853/new-features-coming-to-hearthstone-16-05-2017) coming from Blizzard in a few weeks, I think this is not needed anymore. A new standard has been defined.

**Comment by nosklo** [comment]
Agreed, we now need to be able to read **and** generate the new hash code, though; I found [this code](https://gist.github.com/Tenchi2xh/68f20ed6531b4200a16b1cdcc0e84130) that seems to work. Can you add this code detection to the "import deck" command?

**Comment by supertriodo** [comment]
I'll take a look thx.

**Comment by nosklo** [comment]
It will be a great way to import the deck from hearthstone to arena tracker - I guess it will be the new standard way, it certainly beats playing with fel reavers.... ;)

**Comment by supertriodo** [comment]
Import/Export with Hearthstone done in [v5.1](https://github.com/supertriodo/Arena-Tracker/releases/tag/v5.1)
