### ISSUE TITLE
"Auto create deck" not working

### ISSUE THREAD

**Issue by Amathon** [supertriodo/Arena-Tracker#48]
On 10.12.4 the "auto create deck" function is not working for me.
I followed the instructions to install pyautogui - which installed successfully - but still nothing happens.
Console shows the following error when pressing the button:

`fault	12:27:28.828715 +0200	kernel	IOReturn IOAccelSurface2::surface_unlock_options(enum eLockType, uint32_t): surface is not locked.`

**Comment by supertriodo** [comment]
What is 10.12.4?

I guess you are using Linux. Did you download the static binary or the AppImage binary?

**Comment by Amathon** [comment]
Sorry, Mac OS Sierra 10.12.4. I'm using the 4.51 binary

**Comment by supertriodo** [comment]
Ah ok. It seems there's some kind of bug related to that with the newer  OSX version.
https://apple.stackexchange.com/questions/257752/ioaccelsurface2-error-floods-console-macos-10-12-sierra/260221

I compile and test the mac version with a VM with 10.11

I think you'll have to avoid that feature for now.

**Comment by Amathon** [comment]
Alright - thanks for taking a look!

**Comment by supertriodo** [comment]
With import/export with Hearthstone added in [v5.1](https://github.com/supertriodo/Arena-Tracker/releases/tag/v5.1), auto create deck feature has been removed from AT.
