### ISSUE TITLE
Don't put AppImage into a zip

### ISSUE THREAD

**Issue by probonopd** [supertriodo/Arena-Tracker#49]
Please don't put AppImage into a zip like in `Arena.Tracker.v4.51.Linux.AppImage.zip` because this breaks some important AppImage features such as "no unpacking needed" and automatic binary delta updates, among others.
Instead, please offer the .AppImage file for download directly.
Thanks.

**Comment by supertriodo** [comment]
Roger that!

I'll change it for the next release.
