### ISSUE TITLE
Window Position does not reset when display devices are not available

### ISSUE THREAD

**Issue by PiMastah** [supertriodo/Arena-Tracker#5]
I had Arena Tracker v3.22 Windows running on a second monitor. Now I am just using my laptop without an attached monitor and ArenaTracker is positioned off-screen. One would expect to have the tracker windows spawn positioned only on available display devices.

**Comment by supertriodo** [comment]
Noted in my TODO list. In the meanwhile you can fix it reseting all config, pressing ctrl-r

**Comment by PiMastah** [comment]
Thanks for letting me know, that'll do just fine for the moment. Great work, keep it up! :)

**Comment by supertriodo** [comment]
Fixed for the next release v3.24. I'll close this when the release is out.
