### ISSUE TITLE
Missing shared library: libxcb-xinerama0

### ISSUE THREAD

**Issue by bboro** [supertriodo/Arena-Tracker#50]
Hi,

Running 5.0 on Ubuntu 16.04 Xenial LTS has produced the error message about a missing shared library called libxcb-xinerama0. 

To install the missing library on ubuntu just run:
apt-get install libxcb-xinerama0

Just putting it here for visibility, I'm not sure if I'm an exception and was the only one who didn't have this library installed.

**Comment by supertriodo** [comment]
Thx I'll update the install info for ubuntu.
