### ISSUE TITLE
libxcb-xinerama.so.0 missing

### ISSUE THREAD

**Issue by Jawler** [supertriodo/Arena-Tracker#52]
Hello,
I am trying to use V 5.0 Linux on Ubuntu 16.04 LTS. When run from terminal I get the following error:
`./ArenaTracker: error while loading shared libraries: libxcb-xinerama.so.0: cannot open shared object file: No such file or directory`

Edit: Just installed it via `apt-get install libxcb-xinerama` and it works now. Maybe the binary should check for dependencies and notifiy the user if something is missing.

**Comment by supertriodo** [comment]
I'd suggest linux users to download the AppImage.
I'll have to change it the name to specify better that is a linux binary.

The AppImage won't give you dependency problems. If you still want to use the linux static build, you can install the missing dependencies:

`sudo apt-get install libxcb-xinerama0`

**Comment by supertriodo** [comment]
Didn't you need to install libpng12?

**Comment by nicolasvillavicencio** [comment]
This just happen to me and its solved when installed libxcb-xinerama0 what is odd is the problem started when changed the option transparency to Framed and restart AT

**Comment by supertriodo** [comment]
Wow that's really weird. Dependencies shouldn't be conditional.
