### ISSUE TITLE
Card info download taking a long time

### ISSUE THREAD

**Issue by stwaldo** [supertriodo/Arena-Tracker#53]
When starting up an arena run after an update install (to 5.0), AT takes a really long time downloading the card info - sitting on like 10 minutes now, and it's not even half way done.

Rather than download every card at once, could AT download the cards when needed for a draft? Package them in with the tracker?

**Comment by supertriodo** [comment]
You can download all the cards from the latest release, its on a Hearthstone.Cards.zip

For the next version AT will download all the cards in background while you use it, so it hopefully have all of them when you draft an arena, if that's not the case it willl prioritize the cards needed.

**Comment by supertriodo** [comment]
Instruction about where to put the files from the zip are [here](https://github.com/supertriodo/Arena-Tracker#download-windowsmaclinux)

**Comment by supertriodo** [comment]
Hope it helps! Thx for the feedback.

**Comment by stwaldo** [comment]
Did help, thanks! Thanks for the update too

Adam
