### ISSUE TITLE
AT crashes after Hearthstone update

### ISSUE THREAD

**Issue by BrunoAlan** [supertriodo/Arena-Tracker#54]
After drown a few cards AT suddenly closes.

**Comment by EfficiencyVI** [comment]
I can confirm this. The console just says "Segmentation fault" and crashes the program.

**Comment by supertriodo** [comment]
Hotfix on the way.

**Comment by supertriodo** [comment]
[Fixed](https://github.com/supertriodo/Arena-Tracker/releases/tag/v5.01)

Let me know if everything work as expected.
Thx guys!

**Comment by versvs** [comment]
I think the patch solved the issue and this can be resolved :)

**Comment by BrunoAlan** [comment]
Thank you supertriodo! under Linux Mint runs great again
