### ISSUE TITLE
Stuck on Sarting... in Linux

### ISSUE THREAD

**Issue by AgustinCroce** [supertriodo/Arena-Tracker#55]
Hello, I have debian 8, I tried to run the .AppImage but the program got stuck on the Starting... screen for more than 15 minutes.

These are the logs I got

```
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
20:24:58 - MainWindow: Path Arena Tracker Dir: /home/agustinc/.local/share/Arena Tracker
20:24:58 - MainWindow: Platform: Linux AppImage
20:24:58 - MainWindow: Extra: Json Cards --> Trying: https://api.hearthstonejson.com/v1/latest/all/cards.json
20:24:58 - MainWindow: Extra: Json LightForge --> Download from: http://thelightforge.com/api/TierList/Latest?locale=enUS
libpng warning: iCCP: known incorrect sRGB profile
20:24:58 - DeckHandler: Clear Draw List.
20:24:58 - DeckHandler: Deck list cleared.
20:24:58 - DeckHandler: New deck.
20:24:58 - DeckHandler: Json decks file doesn't exists.
```

**Comment by supertriodo** [comment]
Hi,

On Linux during the first run AT tries to find the directories of Hearthstone in your home dir through the find command. This shouldn't take so long but maybe your home dir is huge, try to empty your trash bin and run  AT again.

Cheers.

**Comment by supertriodo** [comment]
Let me know if that doesnt work and I'll try different things.

**Comment by AgustinCroce** [comment]
It worked, I had to let the program 30-45 minutes the first time (with the trash bin empty). But the following times it started fast.

Thank you.
