### ISSUE TITLE
The new font is terrible

### ISSUE THREAD

**Issue by EfficiencyVI** [supertriodo/Arena-Tracker#56]
How can i turn it off? With all letters in CAPS it looks like Comic Sans.

![wtf](https://user-images.githubusercontent.com/8409366/27011451-01751a58-4ebc-11e7-83aa-a613f2fcb704.png)

**Comment by supertriodo** [comment]
https://www.reddit.com/r/ArenaTracker/comments/6fdc65/testing_new_fonts_which_one_is_your_favourite/

**Comment by EfficiencyVI** [comment]
And?

**Comment by diograph** [comment]
really hurts the eyes

**Comment by supertriodo** [comment]
Don't panic guys, I'll work on that! :)

**Comment by supertriodo** [comment]
Choose your font in the new 5.2 version.
