### ISSUE TITLE
Hoping to make time countdown function

### ISSUE THREAD

**Issue by qwe81301** [supertriodo/Arena-Tracker#57]
Hope to make the time countdown function, let the players know how long the remaining time can play cards, thank you!

**Comment by supertriodo** [comment]
I'll add it to my todo list, but it was never a feature I liked :)

**Comment by qwe81301** [comment]
Thank you for your reply, I am looking forward to this useful function.

**Comment by supertriodo** [comment]
I'll add it to the possible list of features to be voted by patrons 5$+

**Comment by qwe81301** [comment]
OK THX!
