### ISSUE TITLE
Clear history

### ISSUE THREAD

**Issue by viennaa** [supertriodo/Arena-Tracker#59]
Is there any way to clear the history? Since the last update it keeps adding games at the end and reopens that on relaunch.

**Comment by supertriodo** [comment]
The number of games shown in the games tab from the last session depends on the number of logs to be kept on your disk and is specified on [zeroToHeroes slider](https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/config-tab.html#zerotohero).

If you set it to min you will only kept the games from your latest arena when you open AT.

Hope this helps :)

**Comment by viennaa** [comment]
Awesome thanks 👍
