### ISSUE TITLE
Main window size

### ISSUE THREAD

**Issue by kleshas** [supertriodo/Arena-Tracker#6]
Mint 17.2.  Works great except I cannot change the width of the main window after I've changed it once.  Now it's stuck at minimum width (arena, Hand,Config,Log, minimize and close icons along the top fill the width but window not wide enough to read Dark Theme, Split Window etc).

Not sure what the rewards icons mean.  Dust is obvious, but the 3 card backs?  Circle icon is gold?

**Comment by supertriodo** [comment]
Thx for your feedback.

About the rewards, I will add some tooltips to make it more clear. Following the order in screen you can see:
* gold - dust - accept
* number of packs - plain cards - golden cards - cancel

About the resize problem, see as a really problematic bug but I haven't be able to reproduce it, and I use Linux Mint :D, let's see if we can find it.

Keep in mind that the deck window cannot change its wide. The main window can though, but cannot be smaller that minimum wide of the top icons.

1) After restarting the app: Are you able to change the wide of the main window? If you can, tell me exactly when you are not able.
2) Try reseting the config of the app (press ctrl-r). Enter all the info again and tell me what happened exactly before being stuck at minimum width.

**Comment by kleshas** [comment]
1) cannot change the width of the main window.  I then tried ctrl-R which reset the width, but as soon as I touched the bottom right corner to change the width, the window snapped to minimum width, and now is unalterable.
When I unchecked "deck window" the main window widened to allow for the extra tab, but again is not alterable.

![arena](https://cloud.githubusercontent.com/assets/10134682/11819574/7942fbbc-a315-11e5-88fa-b23d97586395.png)

**Comment by supertriodo** [comment]
Try some of the older releases to see if is something I have added recently.

**Comment by kleshas** [comment]
3.23 and 3.22 have the same problem (I never used 3.22 before, but I think I remember 3.23 not having this issue).  I'm fairly new to Linux - is there something in the OS that could do this?

**Comment by supertriodo** [comment]
So does 3.23 have the problem in your system or not?
I don't think you have to do anything in your OS.

**Comment by kleshas** [comment]
yes, 3.23 and 3.22 have this issue now.
I just noticed this isn't a problem when the main window is on my main display, only on the secondary display :/

**Comment by supertriodo** [comment]
Ok, great. That's something I can test and probably reproduce and fix.

Is you find something else tell me.

Thanks for your help.

**Comment by supertriodo** [comment]
For now I gues you can resize up to the size you want in the main screen and then move it to the secondary one.

**Comment by supertriodo** [comment]
One last question for my testing:

* Which are the resolutions of your screens?

**Comment by kleshas** [comment]
1920*1200

**Comment by supertriodo** [comment]
The bug is already fixed. It will be part of next release 3.25

It occurs on secondary screens when those screens are at the right of the main screen. Really sneaky :D
