### ISSUE TITLE
HearthStoneCards.zip is missing

### ISSUE THREAD

**Issue by pdrocaldeira** [supertriodo/Arena-Tracker#63]
README points to latest release and there isn't a download link to HearthstoneCards.

I only saw this link at 5.0 version and I don't think there's every card because we have KFT now.

I'm still trying to download but it's really slow.

**Comment by supertriodo** [comment]
[Here you have](https://drive.google.com/open?id=0B7S6qjtH-56hakxnOWpGRnJONjQ), from my own Hearthstone Cards dir.

**Comment by maroru** [comment]
Having a problem where there is an error when trying to download the cards so the arena drafter doesn't work at all. I am also on MacOS so I don't know where to manually put the HSCards directory.

 I have downloaded your Hearthstone cards directory and tried putting them next to both the ArenaTracker.app as well as the ArenaTracker unix executable but it still doesn't detect the images.
This is what it exactly says in the terminal when I try to start an arena draft: 

> 14:29:31 - HSCardDownloader: Reply: UNG_205 - (0) - 0
> libpng error: Read Error
> QImage::scaleWidth: Image is a null image
> 14:29:31 - HSCardDownloader: Failed to save card image to disk: UNG_205
