### ISSUE TITLE
Two same secrets

### ISSUE THREAD

**Issue by D1mon** [supertriodo/Arena-Tracker#64]
You can't play two identical secrets.
in example: two "ice block" and two "spellbender"

![secret1](https://user-images.githubusercontent.com/3872485/30336427-d81ce43a-97ed-11e7-97f4-884ff3fa1195.png)

![secret2](https://user-images.githubusercontent.com/3872485/30336426-d8196df0-97ed-11e7-8a23-35daeab0f4bd.png)

**Comment by supertriodo** [comment]
You can't. But as none of them have been absolutely isolated to just one secret the other one can be any of the other two possibilities. So the possibilities for the second secrets are still 6 options.
