### ISSUE TITLE
[feature] counter for identical card

### ISSUE THREAD

**Issue by D1mon** [supertriodo/Arena-Tracker#66]
Is it possible to make several identical cards not in a new line, but in a subtree and tighter, but with an increase in the counter?

Before:
![card_before](https://user-images.githubusercontent.com/3872485/30337208-3ac810da-97f0-11e7-8f25-253dbccc93dc.png)

After:
![card_after](https://user-images.githubusercontent.com/3872485/30337220-42fd1c3c-97f0-11e7-9b65-9102d1895371.png)

**Comment by supertriodo** [comment]
Not how the BY cards are defined right now. Should need a redesign.

**Comment by supertriodo** [comment]
This has been added to the list of possible features to be voted by patrons tier 5$+

**Comment by supertriodo** [comment]
This has been implemented by https://github.com/supertriodo/Arena-Tracker/commit/24fb82c2cec6467da01bad1595c747eb3a99f8b0

It will be part of Arena Tracker 7.2 releasing soon.
