### ISSUE TITLE
[feature] total wins and losses counter

### ISSUE THREAD

**Issue by D1mon** [supertriodo/Arena-Tracker#73]
"tab rating":
make a total counter for wins and losses
![rating](https://user-images.githubusercontent.com/3872485/30785195-69457cc0-a16b-11e7-92fa-30d27aabd214.png)

**Comment by supertriodo** [comment]
AT is designed with Arena in mind. Although it works with constructed, I prefer to center in the interaction for arena.

Also, keep in mind [patreon](https://www.patreon.com/triodo) suggestions has high priority.
