### ISSUE TITLE
Cards downloading. Really?

### ISSUE THREAD

**Issue by frozenspider** [supertriodo/Arena-Tracker#75]
First let me tell you that I have slow internet with traffic limit. Upon entering arena, Arena Tracker started download card backs. In 4 hours this abomination downloaded 1 GB of data to get 130 MB of cards (I have no idea how, but the firewall shows network activity of every process), around 1700 of them - all in PNG format, with separate golden version of each (obviously because nothing matters without golden images).
After that I decided to restart the program as it seemed to be gradually slowing down the download process. And guess what? All downloaded cards were GONE! Folder `%USERPROFILE%/Arena Tracker/Hearthstone Cards` was empty!
This is NOT OK. That's NOT how you write a software. I can accept horrible UI, card recognition problems, but this...
I'm not intending to touch this shit anymore, ever. I just wanted to give my bit of "feedback". Move along.

**Comment by supertriodo** [comment]
No much else I can do here, other than close this issue, with that constructive feedback...
