### ISSUE TITLE
Some modern distros have no candidate for libpng12.so.0

### ISSUE THREAD

**Issue by versvs** [supertriodo/Arena-Tracker#76]
When trying to run ArenaTracker on a fresh Ubuntu 17.10, it wouldnt run as no candidate package exists that includes this library.

As it is a fresh install, you may need some other libraries as libxcb-xinerama.so.0, but this actually has a candidate and it is not such of an issue.

As Ubuntu 17.10 includes by default libpng16.so.0, a symbolic link from this library to the expected path for the libpng12 equivalent can be set, then ArenaTracker will find the file but will crash because it tries to read a constant no longer exists:

`./ArenaTracker: /usr/lib/x86_64-linux-gnu/libpng12.so.0: version `PNG12_0' not found (required by ./ArenaTracker)`

It is probably not a big deal to update the dependency, but i know almost nothing of C++ and couldnt find how to fix it.

**Comment by supertriodo** [comment]
Have you tried the appimage version?

**Comment by versvs** [comment]
Running the AppImage works as expected.

**Comment by supertriodo** [comment]
The AppImage version was created to avoid dependecies problems in some distros, that's while I keep releasing both linux versions, so it works on all distros.
