### ISSUE TITLE
Not working on Arch Linux

### ISSUE THREAD

**Issue by rieje** [supertriodo/Arena-Tracker#79]
On Arch Linux, latest version, I'm getting the following error: 

> arena-tracker: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

It used to work when I simply execute the binary downloaded from github, but hasn't worked for ~2 weeks now. `libpng` package hasn't been updated since Oct 6, 2017, but ArenaTracker was working ~2 weeks ago.

**Comment by supertriodo** [comment]
I don't really know how to help you. I use Linux Mint for compiling so these problems will be solved when I upgrade to the new Linux Mint in a few months, maybe.

Maybe someone here can give you a way to solve it on Arch Linux. You could also ask to the maintainer of the aur package: https://aur.archlinux.org/packages/arena-tracker/

**Comment by wizbright** [comment]
I'm also an Arch user and I have had no such problems with running the binary on my system. Even with the latest build from @supertriodo 's patreon.

**Comment by loathingKernel** [comment]
You can use my [PKGBUILD](https://gist.github.com/loathingKernel/68e23997f0e2c10aa2e80a6302c1fd99) to compile the latest  from github on Arch.

@supertriodo I have a question though, what is the proper name for Arena Tracker? I see you are using ArenaTracker in the source but the repo is named Arena-Tracker. Arch requires lowercase names for packages, so which one should be used? This also creates a discrepancy with the resulting binary which uses a different case than the package. I could rename the binary and the related icon/desktop files but this has the side-effect of changing the WM_CLASS value of the window, which can mess up the configuration of a few programs that use it, such as awesomewm in my case.

**Comment by supertriodo** [comment]
@loathingKernel 
I'd say ArenaTracker. Whichever you choose don't change the binary name ArenaTracker, that is important for the auto-updater feature, introduced on v6.2 (I'm going to release it today).

**Comment by loathingKernel** [comment]
OK then, I believe the proper way is to lowercase the package name and keep everything else in camel case like the name. Seems to me the cleaner way to handle this. Thank you for the quick response.

**Comment by supertriodo** [comment]
I think we can close this issue as even the original poster got it working :)
