### ISSUE TITLE
[feature] Exact deck name in trackobot stats

### ISSUE THREAD

**Issue by b00n12** [supertriodo/Arena-Tracker#80]
I'am not sure if this is the right place for this request, or if i'd suggest on trackobot:

I think it would be nice if you could provide stats via trackobot using the deck name entered by the user. It would help a great deal to see how one performs with different variations of one deck archetype.

But anyway nice work! And thanks for Linux support!

**Comment by supertriodo** [comment]
I think you should start by [track-o-bot github](https://github.com/stevschmid/track-o-bot). Either way keep in mind the features I develop are chosen by my [patrons](https://www.patreon.com/triodo) (5$+) as a reward for keeping the project alive.

Great to have another linux fan onboard! AT is developed under Linux using QT.
