### ISSUE TITLE
[minor feature request] Make card draft scores also detachable

### ISSUE THREAD

**Issue by rieje** [supertriodo/Arena-Tracker#82]
On the latest update, detachable windows were added, along with the capability of remembering the window position. This is extremely useful, as now you only need to start Hearthstone and Arena-Tracker--no more fussing with the buttons and windows. However, when I start an Arena run, the Deck Score AVG window will popup and I don't use this premium feature (yet), along with the card score window (which I do use). So, I have to close the Score AVG window and position the card score window appropriately every time i start an arena run. 

I think the following are appropriate changes that fit into the model of Arena-Tracker and serves as an addition to the amazing recent update:

* Have an option to enable/disable Deck Score AVG window so it gets launched by default for those who want it and doesn't get launched for those who don't use it.

* Make the card score window like the other detachable windows and its window position saved. Currently, it doesn't have the window position saved. Also, it's not like the other detachable windows in the sense that it can be re-sized. For some reason, it can't and it takes up an large invisible area under the card draft scores. This is not consistent with other detachable windows; more importantly, the invisible area that overlaps the Hearthstone window means I can't position the card draft scores window above the cards during draft as it would prevent me from picking the cards during draft (since it's overlapped by the invisible area). (Disclaimer: I use a tiling window manager on Linux, so I'm not sure if the problem I'm experiencing is unique to my situation, but the proposed solution still makes sense regardless).

**Comment by supertriodo** [comment]
Your first suggestion is already added to the list of possible features to be voted by patrons tier 5$+

About the second point. It's not a goo idea to make the scores window detachable because was designed to be used as an overlay, not as a window. You are not supposed to move it.
