### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by andreiF94** [supertriodo/Arena-Tracker#84]
When I use the force draft button the app crashes and windows shows this message:
"
Runtime Error!
Program: E:\BattleNet\ArenaTracker.exe
This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.
"
What is the problem?

**Comment by supertriodo** [comment]
It seems a problem related to the use of opencv libraries, but it's the first time I see this problem on windows, which windows are you using?

Try to redownload the exe of Arena Tracker just in case.
