### ISSUE TITLE
Minor improvement: It's libpng12-0

### ISSUE THREAD

**Issue by CreamyCookie** [supertriodo/Arena-Tracker#85]
I wondered why I couldn't find the library `libpng12` mentioned on the readme page about how to install it on Linux. The library is actually called `libpng12-0`.

**Comment by supertriodo** [comment]
Thx for the feedback. Fixed ;)

**Comment by CreamyCookie** [comment]
Thank you! :)

Weirdly enough, the tracker doesn't show anything on Linux. I have both dependencies installed. Is there any way I could figure out what is causing this?

**Comment by supertriodo** [comment]
On the first run on linux it will try to find where you have Hearthstone installed and this can be a long process. If it takes more than 5 minutes I suggest to stop AT, then empty your trash bien and start it again.

**Comment by CreamyCookie** [comment]
@supertriodo Thank you! I had indeed set the wrong Logs directory. It's working great now. The only minor problem is that I can't get the overlay to stay on top of the fullscreen window (either normal or virtual desktop fullscreen)..  Shift + Enter also doesn't seem to change that.

**Comment by supertriodo** [comment]
I usually play windowed. Some time ago I was able to play while Hearthstone was in fullscreen with the shift + Enter trick, but not anymore. It plays perfectly windowed anyway.

**Comment by CreamyCookie** [comment]
That's true. I think it's just that it makes it a bit easier to get distracted :sweat_smile: 

Sorry, for asking so many questions. Is there a way to make the main window disappear (minimize seems to minimize the overlays too)?

Again, thank you for the help and this cool application! :)

**Comment by supertriodo** [comment]
You can click the main window in the task bar (at least in cinammon) and it will minimize/deminimize only that window.

**Comment by CreamyCookie** [comment]
Hmm.. yeah that seems a lot harder in Unity (but it's possible I'm missing something). Anyway, I added this to the script that starts the launcher:

    sleep 1
    wmctrl -r "Arena Tracker" -b remove,above # does not stay on top

**Comment by supertriodo** [comment]
What does it do?

**Comment by CreamyCookie** [comment]
It removes the "Always stay on top" flag of the main window (which has the title "Arena Tracker"). So clicking on Hearthstone hides the main window but not the overlay windows.
