### ISSUE TITLE
Copying deck codes doesn't work anymore

### ISSUE THREAD

**Issue by EfficiencyVI** [supertriodo/Arena-Tracker#87]
I get this message in the log no matter what deck I use:

`DeckHandler: Invalid HS deck`

System:
`$ cat /proc/version
Linux version 4.4.0-116-generic (buildd@lgw01-amd64-021) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018`

**Comment by supertriodo** [comment]
It's related to a change made by Blizzard in cards.json

I just fixed it today: https://github.com/supertriodo/Arena-Tracker/commit/9e96c23951c7e60b7545f0564ac957a45c3db333

I thought it was just giving problems with showing class card colors and the correct question mark on secrets.

I'll release a hotfix tomorrow.

Thx for the feedback.

**Comment by EfficiencyVI** [comment]
Cool :+1:

**Comment by EfficiencyVI** [comment]
Fixed! Thank you!
