### ISSUE TITLE
Arcane Keysmith needs to be supported

### ISSUE THREAD

**Issue by rieje** [supertriodo/Arena-Tracker#90]
[Arcane Keysmith](https://www.hearthpwn.com/cards/89426-arcane-keysmith) needs to be supported (it doesn't trigger list of possible secrets).

**Comment by supertriodo** [comment]
I'll look into it. Thx for the feedback.

**Comment by supertriodo** [comment]
Fixed on [this commit](https://github.com/supertriodo/Arena-Tracker/commit/7547a38e44931eaf26950461c25dfcab160f9411)

Ready for next release.
