### ISSUE TITLE
[feature request] Show changelog in prompt window to update

### ISSUE THREAD

**Issue by rieje** [supertriodo/Arena-Tracker#91]
Just a simple request to show the changelog for the latest version of ArenaTracker. It could be something as simple as a URL to the changelog or ideally be shown in the "New version" window which asks the user if he wants to update. Anything beats having to go to thee Arena-Tracker github page to see the latest changes :)

**Comment by supertriodo** [comment]
Hi,
When you update AT, after it restarts it shows a dialog with a short descriptions of the changes plus a link to click for more details. This link will refer you to the [release section](https://github.com/supertriodo/Arena-Tracker/releases/latest) where all the details are specified.

**Comment by rieje** [comment]
Oops, you're right. In my opinion showing it before you update as "upcoming changes" is slightly more useful
