### ISSUE TITLE
Bug with taverns of time

### ISSUE THREAD

**Issue by Daenym** [supertriodo/Arena-Tracker#93]
Hello everyone, 
i want to start this post by thanking everyone for making available on every platform this arena tracker.  I wanted to tell you that, with the new taverns of time in the arena, the scores for the draft are no longer available and it's a bit frustrating. 
Is there going to be an update soon for this new changes and this exciting 3 weeks?
Again thank's a lot and keep up the good workz

**Comment by supertriodo** [comment]
Hi, I updated yesterday the tier score lists with the new cards and the scores should be shown as always.

If you are not seeing them there must be something wrong with your setup. Let me know if it works.

**Comment by Daenym** [comment]
ok but the latest release that i see is dated on may 4th so i don't know if the app is supposed to update automaticly or not

**Comment by supertriodo** [comment]
Yes it's downloaded automatically. Let's make sure you have the latest versions by removing the AT dir/Extra and restart AT which will download all the files again.

**Comment by supertriodo** [comment]
Is AT working during games?

If not:
Try playing a game on solo mode with AT openned (just a couple of turns is enough) and send me the file AT dir/ArenaTrackerLog.txt (use pastebin.com or something similar).

What is exactly failing during the draft, send me a screenshot.

**Comment by Daenym** [comment]
The tracker is working fine in game, but when i iniciate the draft here first pick:
[
![capture d ecran 2018-06-13 a 00 54 04](https://user-images.githubusercontent.com/40174626/41321500-8c42322a-6ea4-11e8-9b43-a6fc4afa17c9.png)
](url)
It start by re-downloading the cards but once done nothing appears on the screen, but when i finish my draft the tracker work normally

**Comment by Daenym** [comment]
"make sure you have the latest versions by removing the AT dir/Extra and restart AT which will download all the files again." 
How can i do that ?

**Comment by supertriodo** [comment]
Ok, forget about removing Extra dir, that won't help with your problem.

The problem you are facing is because AT is not able to find Hearthstone window in your screens.

I have some question/tasks for your:

1. Is this the fist time you use AT? or you have been using it fine before this event (I'm talking about the draft)
2. Do you have several screens? Remove extra screens and try force draft.
3. Go to HOME/Arena Tracker/Extra/ and open arenaTemplate.png so that image is shown on your screen. Use force draft on AT and check that AT find and recognize the 3 cards of the image.

**Comment by Daenym** [comment]
1) It was working fine before the tavers of time (except when i started the draft before lauching AT then it wouldn't find my draft)
3) When i open the file i got this 
![capture d ecran 2018-06-13 a 11 05 32](https://user-images.githubusercontent.com/40174626/41341323-c309504a-6ef9-11e8-9eda-9239aa8c530d.png)
I don't see how to force the draft. Do i have to download the file?

**Comment by supertriodo** [comment]
When I say "HOME/Arena Tracker/Extra/"

I mean in your Mac go to your USER dir, then Arena Tracker, then Extra. You will find arenaTemplate.png image there. Is the same one you linked on the github, but is already on your PC.

**Comment by supertriodo** [comment]
Remember you need to use the button "Force Draft" on AT located at the top of config tab.

**Comment by supertriodo** [comment]
To clarify a little the purpose of the "Force Draft" button. Generally when you start a draft in Hearthstone AT will automatically start the draft process when you select your hero, but if you were on the middle of a draft when started AT then you have to manually force the draft by using that button.

**Comment by supertriodo** [comment]
If you want join my discord and we can chat quicker: https://discord.gg/vVWNDr

**Comment by Daenym** [comment]
Sorry but i don't see such button on my config tab, i can rescan cards but the button is desactivated

**Comment by supertriodo** [comment]
Force Draft button is at the top of config tab.

Check this:
https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/config-tab.html#actions

**Comment by supertriodo** [comment]
For anyone else having the same problem:

Ok, it seems with the new event the background of the arena has changed which makes AT more difficult to recognize where the cards are.

I have update the template used. What you need to do to get the new template is:

Go to [AT dir](https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/installation.html#ATdir) and remove the dir Extra. Then restart AT and it will redownload all Extra again. Now you can go to your draft, if it is already started (you picked the hero) you will have to use "Force draft" to trigger the drafting process.
