### ISSUE TITLE
v6.71 update

### ISSUE THREAD

**Issue by petertkim** [supertriodo/Arena-Tracker#97]
Hey just wondering, each time I download the v6.71 update, ArenaTracker closes, reopens, and I am prompted to download it all over again.

Is the download working properly and can I ignore this prompt?  Or is something going wrong?

Thanks!

**Comment by supertriodo** [comment]
Hi, which OS are you using? If Linux are you using the AppImage version?

**Comment by supertriodo** [comment]
You are probably using the linux appImage version of AT. In the appImage version  I don't know where the binary you are running is (due the the isolated nature of appImage apps), so I can't just overwrite it with the new version as I do on other platforms.

So what I do is to download the new version of AT and save it on your AT dir in ~/.local/share/Arena Tracker

The first time you do this a message pop up explaining the situation and suggesting you to create a shortcut in your Desktop. The shortcut will redirect you to the updated version stored in AT dir. If you keep running AT from your old binary it will keep updating it.

To recreate the shortcut in your Desktop you can use ctrl-s while AT is in focus. If you use the shorcut, you will always use the version on AT dir that will be the one getting updated.

Is this wasn't your case let me know and we will dig deeper on your problem ;)
