### ISSUE TITLE
Cards are not being recognized properly

### ISSUE THREAD

**Issue by javielero** [supertriodo/Arena-Tracker#99]
Hello
The cards offered by hearthstone do not appear on Arena Tracker as options. When you go into the drop down menu, they also don't appear there. It seems as if the cards are being "misbucketed" by Arenatracker. 

Please check the screenshot.

Thank you.
![screen shot 2018-08-22](https://user-images.githubusercontent.com/6392428/44491552-9fd4d780-a62f-11e8-8d60-d00eb143bf0e.png)

**Comment by supertriodo** [comment]
Let's try removing the following dirs:
* USER/Arena Tracker/Extra
* USER/Arena Tracker/Hearthstone Cards

Restart AT and it will redownload the cards and the tierlists. Try again and see if it fails.

**Comment by supertriodo** [comment]
Have you tried to use the refresh botton at the top-left corner? Also keep in mind the detection is done trhough screen capture so until the cards are detected try not to hover the mouse over the cards to avoid the images being covered.

Apart from that I'm really out of ideas, without golden cards AT shouldn't fail at all.

**Comment by javielero** [comment]
I have used the refresh button on the top left, but that doesn't fix it. I normally don't hover over the cards before they are shown. 

Check another example with the same card as picture number 1. 

![screen shot 2018-08-23 at 7 10 45 pm](https://user-images.githubusercontent.com/6392428/44556584-6c19b080-a708-11e8-9001-160973182c77.png)

**Comment by supertriodo** [comment]
Im out of ideas here. Try to use AT in any mode different to frame (check
in config tab). I haven't tested that mode to much and might be the source
of the problem, but I don't really think so.

**Comment by MissJosieAnne** [comment]
I am having this same issue.

**Comment by supertriodo** [comment]
Sometimes AT can fail in the detection (more often with golden cards). You can select in the dropdown list a different candidate with similar colors like shown in this gif: https://i.redd.it/ebedp3h62kfz.gif

**Comment by kenolee92** [comment]
> Sometimes AT can fail in the detection (more often with golden cards). You can select in the dropdown list a different candidate with similar colors like shown in this gif: https://i.redd.it/ebedp3h62kfz.gif

no i'm the same as above. the drop down menu has a few random cards

**Comment by kenolee92** [comment]
![default](https://user-images.githubusercontent.com/46486631/50887997-b1851300-1448-11e9-99f3-7b0e9a97cc56.png)
turned off golden cards, still the same with dropdown having random cards

**Comment by supertriodo** [comment]
I don't know why but in some computers the image recognition is not done optimally leading to false detections. I'm sorry but I haven't yet find a reason for it.

**Comment by kenolee92** [comment]
i get that card downloading bar appear everytime i start drafting. with always the same trl_etc. could it be related to that? been using the tracker for quite some time, never had an issue until that downloading happened

**Comment by supertriodo** [comment]
With this new expansion I had to change the place from where the cards images were downloaded from; before AT used Hearthhead and it now uses Hearthsim.

But Hearthsim doesn't have the golden versions of the cards, so AT never download the golden version of the cards for the latest expansion. But it keeps trying every time you start a draft, that is why you keep seeing this download messages.

For the new set AT won't use the golden version of cards as a template but it should work as always.

**Comment by Anvikk** [comment]
Same issue there tried all the advices but for some cards still doesn't t work. I've notice even for choosing class sometimes at put old % of winning

**Comment by supertriodo** [comment]
Try adding a screenshot to discard some theories.

**Comment by Anvikk** [comment]
> Try adding a screenshot to discard some theories.

![image](https://user-images.githubusercontent.com/23091652/118097769-ade16c80-b405-11eb-8689-ea700593e2b4.jpeg) hs reply stats vs at ![image](https://user-images.githubusercontent.com/23091652/118097804-b9349800-b405-11eb-9320-afe91aed63b5.jpeg) druid is same warlock and priest little off 
![image](https://user-images.githubusercontent.com/23091652/118097852-c9e50e00-b405-11eb-89da-b7c860849305.jpeg)
Last cards is not read properly

**Comment by supertriodo** [comment]
That is not the latest version, remove your exe and use the latest one.
https://github.com/supertriodo/Arena-Tracker/releases/latest

**Comment by Anvikk** [comment]
I downloaded 9.4 version now and same issue ![image](https://user-images.githubusercontent.com/23091652/118118601-bba3eb80-b41f-11eb-9b77-b5d9ea46bb1b.jpeg)![image](https://user-images.githubusercontent.com/23091652/118118655-ce1e2500-b41f-11eb-990a-4e79c3057ecb.jpeg)![image](https://user-images.githubusercontent.com/23091652/118118767-f017a780-b41f-11eb-8779-3d8a58711b25.jpeg)

**Comment by supertriodo** [comment]
Data from HSReplay is downloaded once a day, so it might be sight difference on what you see. Everything is working fine on your end.

**Comment by Anvikk** [comment]
But still cards in the drafts are not always read properly

**Comment by supertriodo** [comment]
Show me a screenshot were that is the case then.

**Comment by Anvikk** [comment]
It’s in the post but here it is again

**Comment by Anvikk** [comment]
The first card is Shown as overconfident ogre but in hs its heroic inkeeper

**Comment by supertriodo** [comment]
Ok, I don't see the shape badly recognized, you can try to remove the dir Hearthstone Cards inside Arena Tracker dir and restart AT to force the redownload of cards.

Either way think that the detection of cards is not a perfect system and for some people (don't know why) fail more often. You can still correct it by using the drop down menu.

**Comment by supertriodo** [comment]
Also make sure to not hide the image of the card during the detection, you can also use the refresh button.

**Comment by Anvikk** [comment]
In drop down menu is not the card which is in the draft
